### ISSUE TITLE
Thumbnail init scale type?

### ISSUE THREAD

**Issue by ParkerK** [Piasy/BigImageViewer#101]
First off, hats off to you on this amazing library, @Piasy. It's so nice to be able to replace several of my classes with such a nice library (and one that's not buggy like my implementation was!)

I was wondering if there was a way to set an initial scale type for the thumbnail, as I would like the lower resolution thumbnails I have to stretch to fit (centerInside) while the higher resolution image loads. I find the sudden change in image sizes a bit jarring.

If you use anything but the default crop type it works, but for some reason centerInside won't stretch the image to fit

**Comment by ParkerK** [comment]
Nevermind, I figured it out, I had to add `     bigImageView.setInitScaleType(BigImageView.INIT_SCALE_TYPE_CENTER_INSIDE)`. While `INIT_SCALE_TYPE_CENTER_INSIDE` is the default for the final image, there doesn't seem to be a default for the thumbnail, so you have to manually set it. 

Not sure if that is intended, or a bug

**Comment by Piasy** [comment]
PR iis welcome :)
