### ISSUE TITLE
Failed to resolve: com.github.piasy:BigImageViewer:1.4.6

### ISSUE THREAD

**Issue by MeiYi2** [Piasy/BigImageViewer#105]
Hi.

I tried to implement BigImageView by:
    implementation 'com.github.piasy:GlideImageLoader:1.4.6'
    implementation 'com.github.piasy:BigImageViewer:1.4.6'

but I have these error:

![grade](https://user-images.githubusercontent.com/10569370/43056368-82a64f14-8e6e-11e8-9271-77c600053bb9.PNG)

Please advice.

Thank you.

**Comment by Piasy** [comment]
Add this to your root project `build.gradle`

```
allprojects {
    repositories {
        maven {
            url  "http://dl.bintray.com/piasy/maven"
        }
    }
}
```
