### ISSUE TITLE
加载长图时的问题

### ISSUE THREAD

**Issue by darkrevier** [Piasy/BigImageViewer#106]
使用的是FrescoImageLoader  第一次加载正常显示，第二次加载出现短暂黑屏问题，而且第二次加载的图片不是撑满屏幕，这是什么原因

**Comment by Piasy** [comment]
请你调试一番吧。

**Comment by Piasy** [comment]
@darkrevier 能否提供一个测试图片，以及有问题的机型列表？

**Comment by leaderliang** [comment]
down 下来之后运行了 demo 在虚拟机和手机上 都不能撑满屏幕 长图的时候，需要做什么设置么？

**Comment by leaderliang** [comment]
`
  mBigImageView.showImage(Uri.parse("http://ww1.sinaimg.cn/mw690/005Fj2RDgw1f9mvl4pivvj30c82ougw3.jpg"));
                mBigImageView.showImage(Uri.parse("http://img.dqdgame.com/FlOY6t63yywhFQAbAF5jmG4TjHC_"));

其中一个是我的长图片，不能撑满屏幕，看你做的 gif 图是可以自动撑满的
`

**Comment by leaderliang** [comment]
`mBigImageView.showImage(Uri.parse("http://ww1.sinaimg.cn/mw690/005Fj2RDgw1f9mvl4pivvj30c82ougw3.jpg"));
mBigImageView.showImage(Uri.parse("http://img.dqdgame.com/FlOY6t63yywhFQAbAF5jmG4TjHC_"));
`
其中一个是我的长图片，不能撑满屏幕，看你做的 gif 图是可以自动撑满的

**Comment by Piasy** [comment]
需要在 xml 里设置 `app:optimizeDisplay="true"`。

**Comment by leaderliang** [comment]
@Piasy 今天 pull 了下代码，看你 17 日更新了代码，之前app:optimizeDisplay 是 false 的。现在运行是可以的了。

**Comment by leaderliang** [comment]
@Piasy 「第一次加载正常显示，第二次加载出现短暂黑屏问题」 这个不是我遇到的问题哦

**Comment by Piasy** [comment]
Close this issue now, feel free to reopen it :)
