### ISSUE TITLE
Wrong image on recyclerview

### ISSUE THREAD

**Issue by SmasSive** [Piasy/BigImageViewer#107]
Hi!
First of all thanks for this great lib! 👍 

I'm using BIV like a gallery, in a recyclerview with a viewpager behaviour and the viewholder is basically a `BigImageView`, the question is that when I'm paginating there is a page that shows a previous image while progress is shown and once the right image is ready, it is shown correctly.

What I expect is that while the image is downloading, no previous image is shown but only the progress.

I've tried to do a `cancel()` in the `onViewRecycled` method of the adapter but with no success... I've read also that another solution could be to do a `setImageDrawable(null)` but AFAIK I don't have access to the `ImageView` right?

What can I do? If you need more info please ask me!
 Thanks a lot!!!

**Comment by SmasSive** [comment]
I've managed this by doing the following:
- On `onViewRecycled` method from adapter I call a holder method named `clear()`
- That `holder.clear()` is a method that gets the `SubsamplingScaleImageView` and then calls to `recycle()`

**Adapter**
```kotlin
  override fun onViewRecycled(holder: GlideGalleryViewHolder) {
    holder.clear()
  }
```
**ViewHolder**
```kotlin
  fun clear() {
    itemView.itemImage.ssiv.recycle()
  }
```

**Comment by Piasy** [comment]
I think that's a good way to solve this problem.

**Comment by Piasy** [comment]
@SmasSive I think calling `ssiv.recycle()` at `onBindViewHolder` is another option.

**Comment by batadamnjanovic** [comment]
Did anyone managed to recycle() a ssiv in RecyclerView with ViewPager successfully?

Calling `ssiv.recycle()` does not work as expected.

**Comment by batadamnjanovic** [comment]
I was managed to make it work by hiding a `BigImageView` in `onBindViewHolder` and to show it when `onMainImageShown` callback is triggered. 
`ssiv.recycle()` didn't work for me.
