### ISSUE TITLE
Why not just use embedded Fresco DefaultDecoder for animated images?

### ISSUE THREAD

**Issue by LomikXP** [Piasy/BigImageViewer#109]
Because using SimpleDraweeView is as downgrading aproaches of using SubsamplingScaleImageView.
I mean there is no zooming, but using Frescos ZoomingDrawees as make another one SubsamplingScaleImageView

**Comment by Piasy** [comment]
Sorry that I don't understand what do you mean :(

Could you please give some code snippet?

**Comment by LomikXP** [comment]
Ok, as done then show :)

**Comment by LomikXP** [comment]
For case of fresco using:
1.50 BigImageView:519
Uri uri = Uri.fromFile(image);
mSSIV.setImage(ImageSource.uri(uri).tiling(determineFormatForTilling(uri)));
add custom method for determine tilling needs
example:
```
public boolean determineFormatForTilling(Uri uri) {
		ImageFormat imageFormat = null;
		try {
			imageFormat = ImageFormatChecker.getInstance().determineImageFormat(HFile.create(uri).getInputStream());
		} catch (IOException e) {
		}
		return DefaultImageFormats.BMP.equals(imageFormat) || DefaultImageFormats.JPEG.equals(imageFormat) || DefaultImageFormats.PNG.equals(imageFormat);
	}
```
other formats will be decoded by fresco to Bitmap without tiling for now

**Comment by LomikXP** [comment]
And, I disabled ImageViewFactory. May be using your ImageInfoExtractor is more correctly.

**Comment by LomikXP** [comment]
```
public final View createMainView(Context context, int imageType, File imageFile,
            int initScaleType) {
        //if (imageType == ImageInfoExtractor.TYPE_STILL_IMAGE) {
            return createStillImageView(context);
        //} else {
        //    return createAnimatedImageView(context, imageType, imageFile, initScaleType);
        //}
    }
```

**Comment by Piasy** [comment]
Close this issue now, feel free to reopen it :)
