### ISSUE TITLE
示例里的Recycler所有的事件都不生效了

### ISSUE THREAD

**Issue by senRsl** [Piasy/BigImageViewer#110]
请问 recycler adapter里 怎么指定事件呀。

谢谢.

**Comment by Piasy** [comment]
不确定你是什么意思，能否详细解说一下？

**Comment by senRsl** [comment]
就是 我发现 示例里的 recyclerview 跟  glide loader 里的 imageView 设置onClickListener,都不起作用了。

不知道是我改的还是不能用默认方式设置，所有点击事件都不生效。

**Comment by senRsl** [comment]
刚找了一下，发现 按照常规的 bigImageView.setOnClickListener(）设置点击时，在bigView类里，mMainView是null,
mMainView是在 doShowImage时赋值的，doShowImage是在bigImageView.setImageLoaderCallback时调用。。。。

也就是说，需要在 bigImageView.setImageLoaderCallback 里 设置bigImageView的event？

这真的不是个bug吗？。。。。。

**Comment by Piasy** [comment]
噢，这是个 bug，应该先把 listener 存起来，创建 SSIV 时设置。

你愿意提交一个 PR 吗？

**Comment by senRsl** [comment]
你自己改吧，我没怎么看你的源码，怕给你改乱了。

谢了。
