### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [Piasy/BigImageViewer#112]
Good day Sir I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before i begin my design. Hoping for your positive feedback. Thanks

**Comment by Piasy** [comment]
That's great.

**Comment by mansya** [comment]
I have designed a logo. which one do you like? the number 2 I use the color of your profile logo on github.
![bigimageviewer](https://user-images.githubusercontent.com/33461607/44245400-b8458c00-a202-11e8-92fe-c9e4ba65a184.png)
with the image logo in the eye circle. explain as if the user of your application can see images as close as they are. as if the picture was in his eyeball.

**Comment by Piasy** [comment]
The second is cool! Could you please create a pull request to add the logo and icon?

**Comment by mansya** [comment]
I have upload all file to this link.
https://drive.google.com/open?id=1CLrxnaPcfzkKS3b5VBVc9PKlw6L637zF
And I have sent [Pull Requests](https://github.com/Piasy/BigImageViewer/pull/114) please check it.

**Comment by Piasy** [comment]
@mansya Merged, thanks!

**Comment by mansya** [comment]
hi sir. little change about logomark. this is a renewal for better. because for the previous logomark it's not good in the icon scene (eyeball) this is only a small part sir.

this is the old one
![logomark black](https://user-images.githubusercontent.com/33461607/44728188-05c8cf80-ab06-11e8-8c80-f3d34f6c1d41.png)

this is new
![logomark black](https://user-images.githubusercontent.com/33461607/44728055-b1bdeb00-ab05-11e8-9100-260ca53ed779.png)

**Comment by Piasy** [comment]
Cool, please open a PR :)

**Comment by mansya** [comment]
no changes to the project sir. :-D. it's just that I changed it to be better if you use it later.

**Comment by Piasy** [comment]
Cool, thanks!
