### ISSUE TITLE
Publish library to a common repository

### ISSUE THREAD

**Issue by SmasSive** [Piasy/BigImageViewer#113]
Hi!

I'd like not to add
```
        maven {
            url  "http://dl.bintray.com/piasy/maven"
        }
```

in the corporate app, so what do you think about to publish the lib artifact to maven central for example?

**Comment by Piasy** [comment]
Bintray offered options to sync to jcenter, but that service is not stable, I'll try to sync it again.

**Comment by Piasy** [comment]
It seems there is a bug about that service, [only FrescoImageLoader is synced](https://jcenter.bintray.com/com/github/piasy/).

Sorry that I have no time for this issue, besides, I don't think adding such a repo is a big deal. :)

**Comment by Bubu** [comment]
Any update on this? Could you try to sync again?

F-Droid builds by default allow only certain maven repositories, jcenter being one of them, so having this there would be very helpful.

**Comment by Piasy** [comment]
Sorry, no update yet.

If you know how to do the sync, please tell me, I can try it.
