### ISSUE TITLE
Max zoom scale?

### ISSUE THREAD

**Issue by DSofter** [Piasy/BigImageViewer#118]
Hello, thanks for the amazing library!

I noticed for some images I can only zoom in a little bit (around 1.5X scale), and for some other images I can zoom in a lot (3X scale or more). Is there a way I can set the max zoom scale?

Thanks!

**Comment by Piasy** [comment]
Please refer to [SSIV's doc](https://github.com/davemorrissey/subsampling-scale-image-view).

**Comment by DSofter** [comment]
@Piasy Thanks!
