### ISSUE TITLE
Determine static webp and animated webp, use SSIV to display static webp

### ISSUE THREAD

**Issue by jthou20121212** [Piasy/BigImageViewer#119]
你好。
 我们在使用过程中发现，webp图片可以正常展示，不能缩放，静态webp图片也不能缩放。另外我们也同样遇到了共享元素的问题。

**Comment by Piasy** [comment]
webp 是用 fresco 的 SimpleDraweeView 显示的，不支持缩放。

共享元素问题，近期我可能没有时间看，能否请你调试一番？

**Comment by jthou20121212** [comment]
使用subsampling-scale-image-view来缩放webp静态图是没有问题的，我们想使用SubsamplingScaleImageView来展示webp的静态图，使用SimpleDraweeView展示webp动态图。BigImageViewer在ImageInfoExtractor中判断了是不是webp，没有区分静态或者动态图，有什么办法可以区分吗? 感谢回复。

**Comment by Piasy** [comment]
在 `ImageInfoExtractor` 里区分动静 webp 是个思路，但我不确定是否可行，能否请你调研一番？

**Comment by jthou20121212** [comment]
查了资料，英文不好，只在https://en.wikipedia.org/wiki/List_of_file_signatures查到gif有gif87a和gif89a两种，webp是RIFF XXXX WEBP，跟现在代码里一致。维基百科提到第15位区分有损无损压缩，没找到怎么区分动静webp。

**Comment by jthou20121212** [comment]
https://developers.google.com/speed/webp/docs/riff_container#animation
我在这里找到一些信息，没有看很明白。

**Comment by Piasy** [comment]
确实 webp 文件头里面可以解析出是否为动态 webp，不过我近期没有时间，我建议你仔细研究一下，提交一个 PR 😄

**Comment by jthou20121212** [comment]
忙的睡觉都觉得奢侈，英语不好，不敢寄太大希望能解决这个问题，尝试其他方案。
转场动画不是biv的锅，ssiv给出了解决办法https://gist.github.com/Uiasdnmb/cd5182d5fb29f7c1969c09ab209e4ed1

**Comment by Piasy** [comment]
@jthou20121212 v1.5.3 is released, check it out!
