### ISSUE TITLE
加载长图的时候宽度问题

### ISSUE THREAD

**Issue by yayaxiong** [Piasy/BigImageViewer#12]
类似微博微信等加载长图的时候，图片的宽度会拉伸到屏幕的宽度，目前使用bigView发现，有的长图是可以撑满全图，而有的不能，比如 地址：[http://a3.qpic.cn/psb?/V13JRZ9E2wKiz3/CXxy9LDEQt0mLeWLkNwImsskMlsFJm4PSBwJxifhthE!/b/dB8BAAAAAAAA&bo=hAH*PxwCFVkFCT0!&rf=viewer_4](url)

**Comment by Piasy** [comment]
好我看一下

**Comment by Piasy** [comment]
@yayaxiong 你是怎么用的？我在 demo 里面加载你提供的这个 url，没有问题呀，我是在模拟器里面测试的，你试试别的手机，看看是不是手机/系统的问题。

**Comment by yayaxiong** [comment]
@Piasy 我再次用你的源码确认了下，仅仅修改了 LongImageActivity 中的图片地址，在部分手机会出现这个问题，我在 DisplayOptimizeListener 这个类的 onReady 方法打印 imageWidth、  imageHeight、 viewWidth、viewHeight，小米3的测试log显示数据分别为  388/16383/1080/1692,显示正常，也就是显示铺满横屏，在三星手机c7和努比亚 z7max 上面测试的数据和小米3一样，但是显示的图片就不是全屏，见截图，用模拟器测试也出现这个问题。
  1、努比亚截图
![default](https://cloud.githubusercontent.com/assets/10447624/20469148/a6d02980-afd8-11e6-9ffe-c5923dd74ffe.jpg)
  2、三星c7截图
![c7](https://cloud.githubusercontent.com/assets/10447624/20469152/ab0337ea-afd8-11e6-968c-01176e68c04c.jpg)
3、模拟器截图，宽度也是1080
![default](https://cloud.githubusercontent.com/assets/10447624/20469155/aeff0158-afd8-11e6-86e5-b7e98995b3a0.png)

**Comment by Piasy** [comment]
好的，过几天我跟进一下。这周太忙估计没时间看了。

你要是能找到原因修复掉，那就太好了！

**Comment by yayaxiong** [comment]
@Piasy ok!

**Comment by Piasy** [comment]
@yayaxiong hi，你是说有问题的手机上面， imageWidth、 imageHeight、 viewWidth、viewHeight 数值都正常，但就是没有放宽到全屏是吗？那这看起来就是 SSIV 的动画出了问题呀，你能不能跟进去看一下动画的执行过程？

**Comment by Piasy** [comment]
@yayaxiong issue 我先关了，有问题随时打开
