### ISSUE TITLE
Wrong Orientation on images - after v1.5.0; (Linked to #95)

### ISSUE THREAD

**Issue by DennyWeinberg** [Piasy/BigImageViewer#128]
After commit [dcc5404776b6dca031e82f9398462612119af001](https://github.com/Piasy/BigImageViewer/commit/dcc5404776b6dca031e82f9398462612119af001), I'm unable to set the orientation of `mSSIV` before loading the image, since `mSSIV` is only set when requested and not anymore in the constructor.

What's the best way doing it now? Must I set an `ImageLoaderCallback` to use `photoView.getSSIV().setOrientation(ORIENTATION_USE_EXIF);` in the `onCacheHit` method?

I'm not sure if this is the way to do it because the Image View already rendered the image and we are changing the orientation setting afterwards.

Could you maybe implement a proper way of doing that?

EDIT:
The solution I provided works. But it's not the best way I imagine.

**Comment by Piasy** [comment]
You should do it in `onSuccess`, because cache miss may happen.
