### ISSUE TITLE
保存gif問題

### ISSUE THREAD

**Issue by Weststreet** [Piasy/BigImageViewer#13]
現在圖片默認是png結尾的，導致保存gif有問題

**Comment by Piasy** [comment]
其实只是文件名。而且如果利用 fresco，当第一次加载完毕之后，后面再加载同一图片，拿到的文件都是没有后缀的。用 glide 的话我没留意过，可能保留了后缀，也可能没有保留。

其实文件的信息都是完整保留的，你可以自己去改后缀名。

**Comment by Piasy** [comment]
当然 BigImageView 没有让 gif 图动起来是另一个问题，并不是后缀名导致的。
