### ISSUE TITLE
如果剔除包内依赖的com.android.support（27.1.0）加载图片会报如下错误，希望可以修复

### ISSUE THREAD

**Issue by YekaterinaCui** [Piasy/BigImageViewer#134]
![image](https://user-images.githubusercontent.com/18550067/47844328-185ccf00-ddfd-11e8-9874-7dcb56c3655d.png)
@Piasy

**Comment by Piasy** [comment]
本库已迁移到 AndroidX，此问题添加依赖即可解决，本库无法处理。

**Comment by YekaterinaCui** [comment]
> 本库已迁移到 AndroidX，此问题添加依赖即可解决，本库无法处理。

好的，谢谢
