### ISSUE TITLE
How can I reset bigImageViewer after display an image?

### ISSUE THREAD

**Issue by leduclinh7141** [Piasy/BigImageViewer#135]
How can I reset bigImageViewer after display an image?

**Comment by Piasy** [comment]
You mean display another image?

**Comment by barisatalay** [comment]
> How can I reset bigImageViewer after display an image?

You can use this method.
"imageView.cancel();"

**Comment by leduclinh7141** [comment]
Thank you for your reply. I wanted to reset bigImage to initiate state that bigImage does not display anything. I found a method bigImage.removeAllViews() that solved my problem.
