### ISSUE TITLE
can i load image from drawable ?

### ISSUE THREAD

**Issue by 8991hnim** [Piasy/BigImageViewer#136]
i used this func to get uri from resource but when i add this uri to biv it fail, any help? please
public Uri getUriToResource(@NonNull Context context,
                                @AnyRes int resId)
            throws Resources.NotFoundException {
        /** Return a Resources instance for your application's package. */
        Resources res = context.getResources();
        Uri resUri = Uri.parse(ContentResolver.SCHEME_ANDROID_RESOURCE +
                "://" + res.getResourcePackageName(resId)
                + '/' + res.getResourceTypeName(resId)
                + '/' + res.getResourceEntryName(resId));
        /** return uri */
        return resUri;
    }

**Comment by Piasy** [comment]
Please try to reproduce it at demo app, and do some debug. PR is welcome!
