### ISSUE TITLE
How to disable ssiv tiling?

### ISSUE THREAD

**Issue by JoxC** [Piasy/BigImageViewer#137]
First thanks for this great library.

Disable tiling in SSIV is set when setImage like,
`imageView.setImage(ImageSource.asset("map.png").tilingDisabled());`
But in BigImageViewer, setImage seems hard-coded without any other configuration. I don't know how to disable tiling.

**Comment by Piasy** [comment]
Currently BIV doesn't have such API, but you can provide your custom SSIV class, which could disable tiling by overriding the `setImage` method.

**Comment by JoxC** [comment]
Thanks for your reply. You could delete this issue.
