### ISSUE TITLE
Compile Error when I Migrate to AndroidX

### ISSUE THREAD

**Issue by 371280835** [Piasy/BigImageViewer#140]
Multidex Error

**Comment by Piasy** [comment]
Please provide full error message.

**Comment by Piasy** [comment]
The ProgressPieIndicator module seems to be the reason: `Caused by: com.android.tools.r8.errors.CompilationError: Program type already present: com.github.piasy.biv.indicator.progresspie.BuildConfig`.

Could you please try to remove it from dependency?

**Comment by 371280835** [comment]
The ProgressPieIndicator module is the reason.When I remove it from dependency, the problem is solved. Thank you!

**Comment by Piasy** [comment]
I create a new project, and add all modules of BIV, if I don't add these two lines into gradle.properties, it will fail with `Program type already present` error:

```
android.useAndroidX=true
android.enableJetifier=true
```

but if I add these two lines, it won't fail.

So I believe there is something wrong it your project's AndroidX setting, not BIV itself.
