### ISSUE TITLE
Program type already present: com.github.piasy.biv.loader.fresco.BuildConfig

### ISSUE THREAD

**Issue by 550609334** [Piasy/BigImageViewer#142]
使用fresco也出现了同样的问题，androidX支持我是打开的，并且确认有效。 
另外本来我是准备用glide的加载器的，但是由于我的项目的宿主的glide是3.8  而你的项目的glide是4.8 ，我无法升级我的宿主应用的glide(别的团队维护)，所以导致了冲突。 看看能不能出个glide3.8的版本？ 

有空看下fresco这个问题哈！ 谢谢。

**Comment by Piasy** [comment]
源码都在这里了，欢迎你解决问题后提交 PR :)

**Comment by Piasy** [comment]
Please track #144
