### ISSUE TITLE
fresco loader dont play gif file 

### ISSUE THREAD

**Issue by sjdlfajdlfe** [Piasy/BigImageViewer#143]

**Comment by Piasy** [comment]
Could you please try the same url with demo project?

**Comment by tt-aali** [comment]
Any updates on this? I am having the same issue (with glide)

**Comment by Piasy** [comment]
@tt-aali Could you please try the same url with demo project?

**Comment by Piasy** [comment]
Closing it now, feel free to reopen it if necessary.
