### ISSUE TITLE
Program type already present: com.github.piasy.biv.loader.glide.BuildConfig

### ISSUE THREAD

**Issue by YekaterinaCui** [Piasy/BigImageViewer#144]
![image](https://user-images.githubusercontent.com/18550067/51243341-3d54ed00-19bd-11e9-960b-c9efa8f74575.png)
![image](https://user-images.githubusercontent.com/18550067/51243399-71c8a900-19bd-11e9-9632-b0c5c505ba28.png)

按照您之前的解决方法，在AS 3.3 / gradle 4.10.1 / build tools 3.3.0的配置下依旧报错

**Comment by Piasy** [comment]
能否提供一个可复现的 demo 工程？

**Comment by jongha** [comment]
I'm having the same issue after upgrade Android Studio 3.3

**Comment by jas0nchen** [comment]
我看了下依赖库的结构，有两个BigImageViewer。
移除 implementation 'com.github.piasy:GlideImageLoader:1.5.6'
只保留 implementation 'com.github.piasy:BigImageViewer:1.5.6'

**Comment by Piasy** [comment]
@jongha Could you please provide a minimum project that will reproduce this error?

**Comment by jongha** [comment]
@Piasy Okay. I'll try it in my free time.

**Comment by zqr95518** [comment]
```
   implementation 'com.github.bumptech.glide:glide:4.8.0'
    implementation 'com.github.piasy:BigImageViewer:1.5.6'
    implementation 'com.github.piasy:ProgressPieIndicator:1.5.6'
    implementation 'com.github.piasy:GlideImageLoader:1.5.6'
    implementation 'com.github.piasy:GlideImageViewFactory:1.5.6'
    implementation 'com.davemorrissey.labs:subsampling-scale-image-view:3.10.0'
```
这样都是可以运行的，但是
```
maven {
            url "http://dl.bintray.com/piasy/maven"
        }
```
必须放在第一个

**Comment by NeVaDaAAA** [comment]
我也同时又这个问题

**Comment by ff0o0** [comment]
只添加 implementation 'com.github.piasy:BigImageViewer:1.5.6，别的都不加。

GlideImageLoader里有BigImageViewer，BigImageViewer里包含GlideImageLoader，所以会报这个错。

有个疑问，BigImageViewer里为什么会有GlideImageLoader、FrescoImageLoader等？

**Comment by zqr95518** [comment]
全加上去都可以的，但是你maven仓库顺序得改下，要放第一个

**Comment by jongha** [comment]
@zqr95518 Good, I fixed it in your way.

**Comment by Piasy** [comment]
@zqr95518 @jongha Could you please share a minimum project that could reproduce this problem? Thanks!

**Comment by Piasy** [comment]
I didn't reproduce it :(

**Comment by TpOut** [comment]
thank you. change the maven order has effect

**Comment by lianyuchen** [comment]
> 全加上去都可以的，但是你maven仓库顺序得改下，要放第一个

maven的顺序为什么会影响这个呢？求教

**Comment by Piasy** [comment]
Gradle/Android Gradle plugin 的 bug 吧

**Comment by zqr95518** [comment]
我也很纳闷啊，估计是哪个资源站上有错误的pom吧

**Comment by chrisrohitbrendan** [comment]
I'm not very good with gradle, but `'com.github.piasy:BigImageViewer:1.5.6'` already contains the `GlideImageLoader` module included, so I'm guessing it's causing a conflict

I checked dependencies using `gradlew app:dependencies`

**Comment by Pigcasso** [comment]
问题解决了。
改成下面这样就好了：
![Jietu20190324-115711](https://user-images.githubusercontent.com/5566667/54874734-2bb01b80-4e2c-11e9-9a2a-1bf145994d8f.jpg)
原来把`maven {url "http://dl.bintray.com/piasy/maven"}`放在最后就会出现Program type already present，不明白原因

**Comment by Piasy** [comment]
Closing it now, feel free to reopen it if necessary.
