### ISSUE TITLE
为什么会在100%停留比较久

### ISSUE THREAD

**Issue by linfeizheng** [Piasy/BigImageViewer#148]
demo中，圈圈转到99%之后就开始很慢，我用一张3M的长图测试，时间在图中
![1](https://user-images.githubusercontent.com/9878167/55468701-87ea1b00-5636-11e9-8916-7f5ff17ea16d.png)
![2](https://user-images.githubusercontent.com/9878167/55468702-8882b180-5636-11e9-98ae-c13f8e39478d.png)
![3](https://user-images.githubusercontent.com/9878167/55468703-8882b180-5636-11e9-8b2e-6004d37b0714.png)

**Comment by Piasy** [comment]
你用的 fresco 吧？fresco 就是这德行。。。

**Comment by linfeizheng** [comment]
有啥可行的解决办法吗 ，大神

**Comment by Piasy** [comment]
Fresco 官方好像有此问题的 issue，你可以搜搜看。
