### ISSUE TITLE
加载横着的超长图有个小问题！

### ISSUE THREAD

**Issue by RockyQu** [Piasy/BigImageViewer#149]

**Comment by RockyQu** [comment]
当设置 app:initScaleType="centerCrop" 时加载竖着的超长图可以填满屏幕，但是横着的超长图不能填满，这种情况怎么办？

**Comment by RockyQu** [comment]
图片链接用的是 http://ww1.sinaimg.cn/mw690/005Fj2RDgw1f9mvl4pivvj30c82ougw3.jpg

**Comment by RockyQu** [comment]
我自己把它下载下来，弄成了横着的

**Comment by RockyQu** [comment]
手机小米8

**Comment by RockyQu** [comment]
<com.github.piasy.biv.view.BigImageView
        android:id="@+id/mBigImage"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:initScaleType="centerCrop"
        app:optimizeDisplay="true" />

控制属性

**Comment by RockyQu** [comment]
图片加载用的是Glide

**Comment by Piasy** [comment]
请问问题是否已经解决？若没有，能否提供一个可复现的 demo 项目？

**Comment by RockyQu** [comment]
你好，目前没有解决，就用你的demo就行，你就把上面的链接的图片保存成横着的放进去加载，试一试就知道了

**Comment by Piasy** [comment]
好，晚点我试一下

**Comment by Piasy** [comment]
@RockyQu 你说的横图没有填满，是指横图没有上下填满是吧？如果是这个问题的话，那是因为竖长图左右填满是有个[特殊逻辑处理的](https://github.com/Piasy/BigImageViewer/blob/master/BigImageViewer/src/main/java/com/github/piasy/biv/utils/DisplayOptimizeListener.java)，但是横长图没有这样一个上下填满的处理逻辑，所以这是符合预期的。

如果你有兴趣，可以把这个类的逻辑稍作修改，使得横长图也能自动上下填满，欢迎提交 PR :)

**Comment by RockyQu** [comment]
了解了，谢谢

**Comment by Piasy** [comment]
Closing it now, feel free to reopen it if necessary.
