### ISSUE TITLE
recyleview 嵌套 BigImageView

### ISSUE THREAD

**Issue by lyy90** [Piasy/BigImageViewer#152]
recleview 嵌套 bigimageview，默认不能item 不能全屏展示，
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.dafengcar.video.view.BigImage.view.BigImageView
        android:id="@+id/itemImage"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:initScaleType="fitCenter"
        app:optimizeDisplay="true"
        />

</LinearLayout>

     BigImageView bigImageView = helper.getView(R.id.itemImage);
        //bigImageView.setProgressIndicator(new ProgressPieIndicator());
        bigImageView.setInitScaleType(BigImageView.INIT_SCALE_TYPE_CUSTOM);
        bigImageView.setTapToRetry(true);
        bigImageView.setImageViewFactory(viewFactory);
        bigImageView.showImage(Uri.parse(item.getAddress_show()));

我是这样设置的

**Comment by lyy90** [comment]
滑动一下就可以item 就充满啊，怪的一比

**Comment by Piasy** [comment]
请问问题是否已经解决？若没有，能否提供一个可复现的 demo 项目？

**Comment by Piasy** [comment]
Closing it now, feel free to reopen it if necessary.
