### ISSUE TITLE
Duplicate class issue when try to build app with Glide lib

### ISSUE THREAD

**Issue by joaogalli** [Piasy/BigImageViewer#153]
Hi, I have added both these dependencies, and already tried removing one of them. 
`implementation 'com.github.piasy:BigImageViewer:1.5.7'
// load with glide
implementation 'com.github.piasy:GlideImageLoader:1.5.7'`

When I try to build my app I get a Duplicate Code error message for various classes:
`
Duplicate class com.github.piasy.biv.loader.glide.BuildConfig found in modules classes.jar (com.github.piasy.BigImageViewer:GlideImageLoader:1.5.7) and classes.jar (com.github.piasy:GlideImageLoader:1.5.7)
Duplicate class com.github.piasy.biv.loader.glide.GlideCustomImageLoader found in modules classes.jar (com.github.piasy.BigImageViewer:GlideImageLoader:1.5.7) and classes.jar (com.github.piasy:GlideImageLoader:1.5.7)
Duplicate class com.github.piasy.biv.loader.glide.GlideImageLoader found in modules classes.jar (com.github.piasy.BigImageViewer:GlideImageLoader:1.5.7) and classes.jar (com.github.piasy:GlideImageLoader:1.5.7)
Duplicate class com.github.piasy.biv.loader.glide.GlideImageLoader$1 found in modules classes.jar (com.github.piasy.BigImageViewer:GlideImageLoader:1.5.7) and classes.jar (com.github.piasy:GlideImageLoader:1.5.7)
Duplicate class com.github.piasy.biv.loader.glide.GlideLoaderException found in modules classes.jar (com.github.piasy.BigImageViewer:GlideImageLoader:1.5.7) and classes.jar (com.github.piasy:GlideImageLoader:1.5.7)
Duplicate class com.github.piasy.biv.loader.glide.GlideModel found in modules classes.jar (com.github.piasy.BigImageViewer:GlideImageLoader:1.5.7) and classes.jar (com.github.piasy:GlideImageLoader:1.5.7)
Duplicate class com.github.piasy.biv.loader.glide.GlideProgressSupport found in modules classes.jar (com.github.piasy.BigImageViewer:GlideImageLoader:1.5.7) and classes.jar (com.github.piasy:GlideImageLoader:1.5.7)
Duplicate class com.github.piasy.biv.loader.glide.GlideProgressSupport$1 found in modules classes.jar (com.github.piasy.BigImageViewer:GlideImageLoader:1.5.7) and classes.jar (com.github.piasy:GlideImageLoader:1.5.7)
Duplicate class com.github.piasy.biv.loader.glide.GlideProgressSupport$DispatchingProgressListener found in modules classes.jar (com.github.piasy.BigImageViewer:GlideImageLoader:1.5.7) and classes.jar (com.github.piasy:GlideImageLoader:1.5.7)
Duplicate class com.github.piasy.biv.loader.glide.GlideProgressSupport$OkHttpProgressResponseBody found in modules classes.jar (com.github.piasy.BigImageViewer:GlideImageLoader:1.5.7) and classes.jar (com.github.piasy:GlideImageLoader:1.5.7)
Duplicate class com.github.piasy.biv.loader.glide.GlideProgressSupport$OkHttpProgressResponseBody$1 found in modules classes.jar (com.github.piasy.BigImageViewer:GlideImageLoader:1.5.7) and classes.jar (com.github.piasy:GlideImageLoader:1.5.7)
Duplicate class com.github.piasy.biv.loader.glide.GlideProgressSupport$ProgressListener found in modules classes.jar (com.github.piasy.BigImageViewer:GlideImageLoader:1.5.7) and classes.jar (com.github.piasy:GlideImageLoader:1.5.7)
Duplicate class com.github.piasy.biv.loader.glide.GlideProgressSupport$ResponseProgressListener found in modules classes.jar (com.github.piasy.BigImageViewer:GlideImageLoader:1.5.7) and classes.jar (com.github.piasy:GlideImageLoader:1.5.7)
Duplicate class com.github.piasy.biv.loader.glide.ImageDownloadTarget found in modules classes.jar (com.github.piasy.BigImageViewer:GlideImageLoader:1.5.7) and classes.jar (com.github.piasy:GlideImageLoader:1.5.7)
Duplicate class com.github.piasy.biv.loader.glide.PrefetchTarget found in modules classes.jar (com.github.piasy.BigImageViewer:GlideImageLoader:1.5.7) and classes.jar (com.github.piasy:GlideImageLoader:1.5.7)
`

**Comment by Piasy** [comment]
See #141
