### ISSUE TITLE
I used Glide to load image, the image is being rotated

### ISSUE THREAD

**Issue by cai9311** [Piasy/BigImageViewer#154]
The link is http://wefootball.oss-cn-shanghai.aliyuncs.com/upload/backend/2019-06-06/94f44a8ff7e245bf9025aa6b4e699a32.jpg
When I used GlideImageLoader,Is is rotated.

**Comment by Piasy** [comment]
@cai9311 That should be a SSIV issue, please file an issue [here](https://github.com/davemorrissey/subsampling-scale-image-view/issues/new) with the sample image link.

**Comment by DennyWeinberg** [comment]
I did that:

```
            photoView.setImageLoaderCallback(new ImageLoader.Callback() {
                @Override
                public void onCacheHit(int imageType, File image) {
                    photoView.getSSIV().setOrientation(ORIENTATION_USE_EXIF);
                }

                @Override
                public void onCacheMiss(int imageType, File image) {

                }

                @Override
                public void onStart() {

                }

                @Override
                public void onProgress(int progress) {

                }

                @Override
                public void onFinish() {

                }

                @Override
                public void onSuccess(File image) {

                }

                @Override
                public void onFail(Exception error) {

                }
            });
```

Just for information

**Comment by Piasy** [comment]
@DennyWeinberg You should move your code into `onFinish` or `onSuccess`, although GlideLoader won't fire `onCacheMiss`, which means `onCacheHit` could work.

**Comment by DennyWeinberg** [comment]
I use a custom Glide Loader so it worked in my case because I call `onCacheHit` manually...

**Comment by hereisderek** [comment]
I don't really understand why not extracting the orientation automatically when first load.
