### ISSUE TITLE
implementation 'com.github.piasy:GlideImageLoader:1.5.7'

### ISSUE THREAD

**Issue by emailsubjekt** [Piasy/BigImageViewer#155]
ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.github.piasy:GlideImageLoader:1.5.7.
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.github.piasy:GlideImageLoader:1.5.7.
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.github.piasy:GlideImageLoader:1.5.7.
Show Details
Affected Modules: app

**Comment by mo0n1andin** [comment]
use
`        
repositories {
    maven { url "https://dl.bintray.com/piasy/maven" }
}
`
