### ISSUE TITLE
Is the decode format PREFER_ARGB_8888 possible?

### ISSUE THREAD

**Issue by DennyWeinberg** [Piasy/BigImageViewer#156]
As you can see here:
https://imgur.com/a/dEKxhVQ

I have some issues with the number of colors used for decoding the photo.
Is it possible to improve that?

The zoom quality is awesome and your library works very well!

My code:

```
BigImageView photoView = viewDetailsContent.findViewById(R.id.photoView);
photoView.showImage(uri);
```

**Comment by Piasy** [comment]
Please try to find this feature in [SSIV](https://github.com/davemorrissey/subsampling-scale-image-view)'s doc, it it has this feature, you can do it like this:

```java
 biv.setImageLoaderCallback(new ImageLoader.Callback() {
                @Override
                public void onCacheHit(int imageType, File image) {
                }

                @Override
                public void onCacheMiss(int imageType, File image) {

                }

                @Override
                public void onStart() {

                }

                @Override
                public void onProgress(int progress) {

                }

                @Override
                public void onFinish() {

                }

                @Override
                public void onSuccess(File image) {
                    photoView.getSSIV().// call whatever you need on SSIV
                }

                @Override
                public void onFail(Exception error) {

                }
            });
```

**Comment by DennyWeinberg** [comment]
Yeah right, thanks!

**Comment by DennyWeinberg** [comment]
`photoView.getSSIV().setBitmapDecoderFactory(new CompatDecoderFactory<>(SkiaImageDecoder.class, Bitmap.Config.ARGB_8888));`

**Comment by DennyWeinberg** [comment]
@Piasy ,isn't it too late to do that?
`mSSIV` is set in `doShowImage`, `doShowImage` is called before `onCacheHit` (which is where I need to interact because I call that method in my custom Glide Loader).
At least my code simply does nothing. The result is the same.

**Comment by DennyWeinberg** [comment]
I debugged the code and I'm right, `mSSIV = (SubsamplingScaleImageView) mMainView;` is called right before `mSSIV.setImage(ImageSource.uri(Uri.fromFile(image)));`. That means that we don't have any possibility to inject our decoder before the `setImage` method is called.
I think we need a new callback...
What do you think?

**Comment by WarriorYu** [comment]
感谢作者的这个开源库。我有个问题：我们不能保证图片没有透明通道，大图显示也是为了更清晰的查看图片，所以能有个设置ARGB_8888的方法很重要，既然有人提交这部分代码了，为什么坚持不用呢？

**Comment by Piasy** [comment]
> Thanks for your contribution! But I think you can use the biv.setImageViewFactory API, in which you can create your own SSIV, so you can set decoder factory here.
