### ISSUE TITLE
BigImageViewer+HorizontalScrollView加载横向长图后半段拖动卡顿

### ISSUE THREAD

**Issue by DingZugeng** [Piasy/BigImageViewer#159]
你好，我使用BigImageViewer+HorizontalScrollView加载一张网络上的宽高为15673x1080（7MB）像素的图片，使用Glide方式加载。在模拟器里拖动全程都很流畅，但是在真机上前半段拖动正常，后半段明显感觉卡顿了。只要拖回图片前半段就正常了。logcat里没发现有什么有意义的提示信息。请问这种情况有没有碰到过呢？或者能否提供一个思路如何去解决它。谢谢。

**Comment by Piasy** [comment]
没有试过这种场景，不过有可能是 HorizontalScrollView 导致整个宽图都被加载，内存占用增加导致。

你看看 monitor 里的内存或 CPU 情况？

**Comment by Piasy** [comment]
Closing it now, feel free to reopen if necessary.

**Comment by qq1100** [comment]
我也遇到同样问题，请问如何解决cpu消耗大的问题、

**Comment by qq1100** [comment]
@Piasy

**Comment by Piasy** [comment]
>有可能是 HorizontalScrollView 导致整个宽图都被加载，内存占用增加导致。
>你看看 monitor 里的内存或 CPU 情况？

**Comment by qq1100** [comment]
我用的是RecyclerView。 真机上不卡,模拟器会卡。
