### ISSUE TITLE
无法加载mipmap或drawable中图片吗？

### ISSUE THREAD

**Issue by SharkChao** [Piasy/BigImageViewer#162]

**Comment by SharkChao** [comment]
GlideImgaeLoad可以加载出来，Fresco不可以

**Comment by SharkChao** [comment]
大神，现在FrescoImageLoad无法加载mipmap中图片，而GlideImageLoad无法加载webp动图，这两个问题有办法解决吗？

**Comment by Piasy** [comment]
webp 是 glide 本身不支持。

mipmap 问题，我怀疑是 Uri 创建得不对，欢迎动手调试分析，然后提交 PR。

**Comment by SharkChao** [comment]
> webp 是 glide 本身不支持。
> 
> mipmap 问题，我怀疑是 Uri 创建得不对，欢迎动手调试分析，然后提交 PR。

应该不是Uri创建不对，因为同一个Uri，frescoImageLoad无法加载，GlideImageLoad就可以加载出来。

**Comment by Piasy** [comment]
Closing it now, feel free to reopen it if necessary.
