### ISSUE TITLE
onBeforeSetImage()这个回调方法在哪个版本里，找不到这个方法？

### ISSUE THREAD

**Issue by WarriorYu** [Piasy/BigImageViewer#166]
我看你加上这个方法了，但是我使用1.5.7版本找不到，这是最新的版本了吧？还有，这是唯一一个能设置ARGB_8888的地方吗？项目着急用，麻烦解答一下，谢谢了！

**Comment by Piasy** [comment]
这个 PR 没有合并，此类需求不需要新增这样一个回调，具体可以看 #157 的评论

**Comment by WarriorYu** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    非常感谢你的回复。 #157 的评论我看了，但是不知道评论里biv.setImageViewFactory()这一步的具体实现，能简单指点一下吗？或者有个参考的链接吗？这一类的答案很少，所以还要麻烦你解答一下。 
    
        
            
        
    
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                soldieryu.dev
                            
                    
                        
                            
                                    soldieryu.dev@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2019年08月29日 17:26，Piasy<notifications@github.com> 写道： 


这个 PR 没有合并，此类需求不需要新增这样一个回调，具体可以看 #157 的评论



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Piasy** [comment]
https://github.com/Piasy/BigImageViewer/blob/master/app/src/main/java/com/github/piasy/biv/example/CustomSSIVActivity.java
