### ISSUE TITLE
Android 4.4.4 

### ISSUE THREAD

**Issue by Alexander178** [Piasy/BigImageViewer#168]
Why doesn’t work on Android 4.4.4 ?  Unable to compile! 
Is there a way out for android 4.4.4?

Error:

Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexIndexOverflowException: Cannot merge new index 65544 into a non-jumbo instruction!

**Comment by Piasy** [comment]
why do you think it's the fault of BIV?

**Comment by Alexander178** [comment]
If add to gradle -
compile 'com.github.piasy:BigImageViewer:1.5.7', then
error pops up on android 4.4 emulator, and on the emulator, android 5+ works fine.

if removed - 
compile 'com.github.piasy:BigImageViewer:1.5.7',
then there are no errors and everything works fine on all androids.

Сhecked for Android Studio 2.3.3

**Comment by Piasy** [comment]
That's strange, I have no idea about that now, could you please try to search about the error on the internet and try to fix it?

**Comment by Piasy** [comment]
Closing it now, feel free to reopen it if necessary.
