### ISSUE TITLE
In ViewPager2 just show loading indicator in some cases

### ISSUE THREAD

**Issue by rockyoung** [Piasy/BigImageViewer#177]
I'm using BIV(1.5.7) in ViewPager2(1.0.0-beta04), if the viewpager2 init with the currentItem which is > 1, than previous page will only show the progress indicator, no mater how user scrolled later, the image will never show up.

**Comment by Piasy** [comment]
I hope you could do some debug on it, and submit a bugfix PR :)

**Comment by rockyoung** [comment]
> I hope you could do some debug on it, and submit a bugfix PR :)

I've find the solution here [https://github.com/Piasy/BigImageViewer/blob/master/app/src/main/java/com/github/piasy/biv/example/RecyclerAdapter.java#L50](url)

**Comment by Piasy** [comment]
Great then, I'll update README about this.
