### ISSUE TITLE
用glide 加载图片 没有出现进度显示。

### ISSUE THREAD

**Issue by howezeng** [Piasy/BigImageViewer#18]
mImageView.showImage(Uri.parse(model.getUrl()));
                    mImageView.setProgressIndicator(new ProgressPieIndicator()); 加了这句话无效

**Comment by Piasy** [comment]
是不是图片太小了，你试试加载 demo 里面的那张图

**Comment by Piasy** [comment]
那我先关咯，有新的反馈再打开吧。
