### ISSUE TITLE
mFailureImageClickListener will call the mOnClickListener

### ISSUE THREAD

**Issue by rockyoung** [Piasy/BigImageViewer#180]
I use BigImageView.setOnClickListener(final OnClickListener listener) to finish the Activity when user just tap the BigImageView, everything works fine but it become interesting if the failure image show up, check the source code i found this:
```
if (mOnClickListener != null) {
    mOnClickListener.onClick(v);
}
```
inside the mFailureImageClickListener statement block
https://github.com/Piasy/BigImageViewer/blob/df7453dd2531758d51611dc3905d78c9a15c40a0/BigImageViewer/src/main/java/com/github/piasy/biv/view/BigImageView.java#L122

so, the question is, why must check and invoke the mOnClickListener here? Shouldn't we separate their logic?

**Comment by Piasy** [comment]
That's definitely a flaw of design.

Now I'm thinking, if we enabled tap-to-retry, should we only fire click event when SSIV is clicked, what do you think?

**Comment by rockyoung** [comment]
> Now I'm thinking, if we enabled tap-to-retry, should we only fire click event when SSIV is clicked, what do you think?

I don't think so, what about animated image like gif and webp? as we know they are not displayed by SSIV

**Comment by Piasy** [comment]
You are right, actually the click listener is set to thumbnail and main image, do you think it's a good idea to just bypass the failure image?

**Comment by rockyoung** [comment]
yes, when tap-to-retry is enabled, use mFailureImageClickListener, mOnClickListener otherwise.

**Comment by Piasy** [comment]
Okay, I'll cut a release for that.

**Comment by Piasy** [comment]
`v1.6.1` is released, check it out :)
