### ISSUE TITLE
Does this use OKHttp3?

### ISSUE THREAD

**Issue by EchoTiger** [Piasy/BigImageViewer#186]
Sorry if this is a silly question, but I noticed after using this I had errors from people using versions of Android below APK 21.

After investigating it, it seems that OKHttp3 is being called when using Glide and the only thing I could guess is that it is coming from BigImageViewer.

If this is the case, is there any way to not use OKHttp3 and use something that APK 16 would support?
I'm still a Android newbie when it comes to this stuff, so sorry if this is something normally simple. :)

**Comment by Piasy** [comment]
This is not silly at all.

You could force gradle to use a specific version of OkHttp, by adding this block to your module's build.gradle, please note that it should be added at the top level, not inside any other block:

```gradle

configurations {
  all {
    resolutionStrategy {
      eachDependency { DependencyResolveDetails details ->
        if (details.requested.group == 'com.squareup.okhttp3' &&
            details.requested.name ==
            'okhttp') {
          // OkHttp drops support before 5.0 since 3.13.0
          details.useVersion '3.12.6'
        }
      }
    }
  }
}
```

**Comment by Piasy** [comment]
README updated: https://github.com/Piasy/BigImageViewer/blob/master/README.md#caveats
