### ISSUE TITLE
ImageInfoExtractor 区分动态和静态webp的方案有问题

### ISSUE THREAD

**Issue by LoveRain1997** [Piasy/BigImageViewer#188]
ANIM 位置不是固定的

**Comment by LoveRain1997** [comment]
https://github.com/b4rtaz/android-webp-encoder/blob/master/app/src/main/java/com/n4no/webpencoder/webp/muxer/WebpContainerReader.java

**Comment by Piasy** [comment]
感谢指出，欢迎 PR :)
