### ISSUE TITLE
你好。请问关于缩略图的缩放方式可以自定义吗。

### ISSUE THREAD

**Issue by 447zyg** [Piasy/BigImageViewer#19]
现在的都是满高度。然后从缩略图到原图的那个过程屏幕变化有点突然。很明显的一种过度。。ty！如果是宽图则更明显。。

**Comment by Piasy** [comment]
现在缩略图使用的是 fresco/glide 加载并显示的，而实际大图则是用的 SSIV，它们应该可以统一 scaleType，但是还没做。

欢迎提交 pr 😀

**Comment by Piasy** [comment]
[SSIV 对预览图片有支持](https://github.com/davemorrissey/subsampling-scale-image-view/wiki/03.-Preview-images)，所以也许可以改变现有的缩略图方案。SSIV 自己的缩略图应该不存在“突然变化”的问题，即便有问题也可以调。

**Comment by Piasy** [comment]
@447zyg `v1.2.3` 增加了 `initScaleType` 属性，它可以控制初始时的缩放方式，缩略图会相应使用 `centerCrop` 和 `centerInside`。但由于缩略图和原图尺寸不一样，所以可能实际效果并不明显。

**Comment by 447zyg** [comment]
谢谢～

2016-12-03 18:39 GMT+08:00 Piasy <notifications@github.com>:
