### ISSUE TITLE
How to know cache image is gif or not 

### ISSUE THREAD

**Issue by xiachengcheng** [Piasy/BigImageViewer#195]
I use BigImageView with GlideImageLoader, and I found trouble when save image to sd card. I can get file name by BigImageView.getCurrentImageFile(), but this file name did not contain file suffix, thus I can not identify this image is jpg or gif. Is there any way to know it?

**Comment by Piasy** [comment]
How do you "save image to sd card" with BIV now?

**Comment by xiachengcheng** [comment]
Thanks for your response, It's solved. I thought cache file name would be like 'xxx.gif', but it was actually like 'xxx.o' which did not contain file extension. 
So I just pass the origin file name to do the type judge.

**Comment by SongpolR** [comment]
Can you explain more about this sentence "So I just pass the origin file name to do the type judge"? I try to save an image by BIV via `saveImageIntoGallery()` but the filename always is the name of the caching file with no extension.

**Comment by Piasy** [comment]
I guess he meant app has not only url of the image, but also other info, e.g. filename.
