### ISSUE TITLE
SubsamplingScaleImageView: Failed to initialise bitmap decoder     java.io.IOException: Image failed to decode using JPEG decoder

### ISSUE THREAD

**Issue by minzbox** [Piasy/BigImageViewer#197]
I encounter an issue with android 6 (samsung note 4). When using BIV in recyclerview, some url does not show, and the exception will throw. 
Ex: http://imageinstant.com/data/images/17023/544550/009-fix.jpg
Try in demo and the same error. I dont know why this happen, please help

**Comment by Piasy** [comment]
Maybe you could try to debug in the demo app :)

**Comment by minzbox** [comment]
> Maybe you could try to debug in the demo app :)

If not use in recyclerview, the BIV shows image normally, this issue only happens in recyclerview

**Comment by akay25** [comment]
I'm not facing this issue and I'm using both recyclerview and viewpager for my project
