### ISSUE TITLE
trying to draw too large bitmap

### ISSUE THREAD

**Issue by conghuahuadan** [Piasy/BigImageViewer#198]
hello, use demo, load large gif, report error, gif [link](https://cdn-files.ushknews.com/a-image/flash/63d26433-17a5-4d79-8613-a901aa40170b.gif)

![image](https://user-images.githubusercontent.com/20864280/82802334-48713480-9eb1-11ea-848a-aaa969d2173f.png)

![image](https://user-images.githubusercontent.com/20864280/82802193-119b1e80-9eb1-11ea-86a3-c6a584ee1935.png)

**Comment by Piasy** [comment]
That's the limit of gif drawable library.
