### ISSUE TITLE
小图无法缩放问题

### ISSUE THREAD

**Issue by echohaha** [Piasy/BigImageViewer#20]
我加载一张小图 图片宽高都小于屏幕 结果无法缩放 我想问下是SSIV的问题 还是BigImageViewer的问题

**Comment by Piasy** [comment]
SSIV

**Comment by echohaha** [comment]
是SSIV不支持吗 还是可以设置的呢？

**Comment by Piasy** [comment]
@echohaha [SSIV 可以设置 maxScale](https://github.com/davemorrissey/subsampling-scale-image-view/wiki/07.-Configuration#setmaxscalefloat--setminimumdpiint), 例如 `http://img0.imgtn.bdimg.com/it/u=1404334591,1869466979&fm=21&gp=0.jpg` 这个图片比屏幕小，maxScale 默认是 2，那这个图就无法缩放，但是如果把 maxScale 设置为 10，就能把这个图放大到全屏，且可以略微缩放（但是很模糊）。我有一个想法，加载到的图片都是本地的文件，那么可以先获取图片的尺寸，再根据 view 的大小，设置 maxScale，但是到底是什么比例关系，我暂时没有时间探究和完善。

欢迎提交 pr！😃

**Comment by echohaha** [comment]
好的 非常感谢！！！
