### ISSUE TITLE
BigImageViewer still requires com.android.support

### ISSUE THREAD

**Issue by DrMetallius** [Piasy/BigImageViewer#200]
I can see that the library has migrated to AndroidX, which is great. However, when we turned off Jetifier, we found out that one of the dependencies of BigImageViewer still depends on the old support libraries, namely `com.davemorrissey.labs:subsampling-scale-image-view`. Please replace this dependency with `com.davemorrissey.labs:subsampling-scale-image-view-androidx` so we don't need to resort to manual dependency resolution adjustment.

**Comment by Piasy** [comment]
Why would you turn off jetifier?

**Comment by DrMetallius** [comment]
Because it takes time to process the libraries as any additional build step increases build time. Given that the contributors to this library have already taken the trouble to migrate to AndroidX, I don't see any downsides in switching to another dependency which is completely equivalent, but uses AndroidX as well, and this switch entails almost no changes.
