### ISSUE TITLE
Unable to use the library with minSdkVersion <17

### ISSUE THREAD

**Issue by tom5079** [Piasy/BigImageViewer#204]
```gradle
implementation "com.github.piasy:GlideImageLoader:1.6.7"
```
with minSdkVersion <17 gives

`Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 17 declared in library [pl.droidsonroids.gif:android-gif-drawable:1.2.20]`

by the way, how did you even fit the minSdk 17 library into minSdk14 library? interesting.

**Comment by Piasy** [comment]
If you use fresco flavor, then you can use minSdk14.

**Comment by tom5079** [comment]
Then you should bump up the minSdk of glide libraries, it confused me like hell

**Comment by EvgenyTerebenin** [comment]
Hi! I have such message too 
`Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 17 declared in library [pl.droidsonroids.gif:android-gif-drawable:1.2.20]
`
I use implementation 'com.github.piasy:GlideImageLoader:1.6.7'

**Comment by Piasy** [comment]
> Then you should bump up the minSdk of glide libraries, it confused me like hell

As I said, it's not necessary to use 17 when glide is not used. This kind of bump up should be done in app module, just like what I did in example app module.

**Comment by tom5079** [comment]
Exactly, 

> > Then you should bump up the minSdk of glide libraries, it confused me like hell
> 
> As I said, it's not necessary to use 17 when glide is not used. This kind of bump up should be done in app module, just like what I did in example app module.

Exactly, it means I need to use 17 when I use glide. Then why the hell is the minSdk of the `GlideImageViewFactory` 14?

**Comment by Piasy** [comment]
Ha, nice catch up, I'll update it later, thank you!

**Comment by Piasy** [comment]
But recently I just found that Glide support load gif into normal ImageView, so I'll remove android-gif-drawable dependency instead.

**Comment by tom5079** [comment]
Great, I was wondering why you used separate library for the gif handling when I can just use glide to load gif. Sounds nice 👍

**Comment by Piasy** [comment]
v1.7.0 is released, check it out!
