### ISSUE TITLE
在电视显示的时候，图片的左边有间隙

### ISSUE THREAD

**Issue by paofan** [Piasy/BigImageViewer#212]
电视分辨率3840*2160，目前只有一台电视是这样，其他同样分辨率的电视却可以全屏显示。
        BigImageView bigImageView = new BigImageView(context);
        ViewGroup.LayoutParams params = new ViewGroup.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, 
        ViewGroup.LayoutParams.MATCH_PARENT);
        bigImageView.setLayoutParams(params);
        bigImageView.setInitScaleType(BigImageView.INIT_SCALE_TYPE_FIT_XY);
        bigImageView.setOptimizeDisplay(false);

**Comment by Piasy** [comment]
代码都是开源的，自己调试一下吧。
