### ISSUE TITLE
作者的依赖设置错了吧

### ISSUE THREAD

**Issue by jqorz** [Piasy/BigImageViewer#213]
我新建一个没有任何依赖的项目，项目中的Library是这样的
![搜狗截图20201219163806](https://user-images.githubusercontent.com/16350758/102685110-1a6e8b80-4219-11eb-94ce-cb91f89d9cff.png)
但是我只添加一个`implementation 'com.github.piasy:BigImageViewer:1.6.4'`，项目中的Library就变成了这样
![搜狗截图20201219163828](https://user-images.githubusercontent.com/16350758/102685130-31ad7900-4219-11eb-8f5b-b2b85c9665ab.png)（PS:这只是一部分，下面还有好多）
其实我只用到了Glide，为啥作者把其他图片框架的，比如fresco都加进来了？

**Comment by Piasy** [comment]
你可能哪里搞错了，`com.github.piasy:BigImageViewer` 只依赖了 SSIV，应该不会有 glide 和 fresco 的。

**Comment by jqorz** [comment]
> 你可能哪里搞错了，`com.github.piasy:BigImageViewer` 只依赖了 SSIV，应该不会有 glide 和 fresco 的。

但是实际上我的测试项目只引用了`com.github.piasy:BigImageViewer`，上面的图就是引用前后对比。作者可以建个空项目测试一下，切到Project看下依赖就能看到了

**Comment by g19980115** [comment]
我试了下也是这样，我只加了一行这个`implementation 'com.github.piasy:BigImageViewer:1.7.0'`，全都依赖进来了。
改成`com.github.piasy.BigImageViewer:BigImageViewer:1.7.0` 就不会，作者要改下readme

**Comment by g19980115** [comment]
这是我打印的依赖项详情

![image](https://user-images.githubusercontent.com/25760230/103204060-7039e680-4931-11eb-8480-342c74956b54.png)

**Comment by g19980115** [comment]
其它的选配也不对，全都要加上`.BigImageViewer`。
例：`com.github.piasy:GlideImageLoader:1.7.0` 改成 `com.github.piasy.BigImageViewer:GlideImageLoader:1.7.0`
```Java
implementation 'com.github.piasy.BigImageViewer:BigImageViewer:1.7.0'

// load with fresco
implementation 'com.github.piasy.BigImageViewer:FrescoImageLoader:1.7.0'

// load with glide
implementation 'com.github.piasy.BigImageViewer:GlideImageLoader:1.7.0'

// progress pie indicator
implementation 'com.github.piasy.BigImageViewer:ProgressPieIndicator:1.7.0'

// support thumbnail, gif and webp with Fresco
implementation 'com.github.piasy.BigImageViewer:FrescoImageViewFactory:1.7.0'

// support thumbnail and gif with Glide
implementation 'com.github.piasy.BigImageViewer:GlideImageViewFactory:1.7.0'
```
