### ISSUE TITLE
Wouldn't it be important to stay away from Bintray?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Piasy/BigImageViewer#220]
It says we should use :

```
            url  "https://dl.bintray.com/piasy/maven"
```

But Bintray, as well as jcenter - will be shut down:
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Various repositories already migrated, either to maven-central or to Jitpack.

Please consider migrating too.

**Comment by ogartaganis** [comment]
I'm not sure if it's related or not, but I'm getting 
```
'http://dl.bintray.com/piasy/maven/com/github/piasy/GlideImageLoader/1.7.1/GlideImageLoader-1.7.1.pom'. Received status code 403 from server: Forbidden
```

is there an issue already with importing the library?

**Comment by Piasy** [comment]
@ogartaganis  You should use https.

**Comment by ogartaganis** [comment]
> @ogartaganis You should use https.

Thanks for the answer. This was actually a message from Android Studio and I don't control the url. However, the issue was resolved by itself after restarting, false alarm 👍

**Comment by SmasSive** [comment]
Hi, do you have an ETA when will the library be migrated?

**Comment by Piasy** [comment]
I'm trying it today.

**Comment by AndroidDeveloperLB** [comment]
Weird. I use this today without bintray written anywhere:
```
implementation 'com.github.piasy.BigImageViewer:GlideImageLoader:1.7.1'
```

**Comment by Piasy** [comment]
It's available in maven central now, please read the [Add the dependencies](https://github.com/Piasy/BigImageViewer#add-the-dependencies) part carefully.
