### ISSUE TITLE
旧的项目使用旧的库无法引用了

### ISSUE THREAD

**Issue by Frank-Gao** [Piasy/BigImageViewer#224]
Error:Could not GET 'http://dl.bintray.com/piasy/maven/com/android/support/support-annotations/27.1.1/support-annotations-27.1.1.pom'. Received status code 403 from server: Forbidden
<a href="toggle.offline.mode">Enable Gradle 'offline mode' and sync project</a>

你好，旧的项目使用旧的库无法引用了，麻烦帮忙解决一下。

**Comment by Piasy** [comment]
Okay, I'll try to release a no AndroidX version to maven central tomorrow morning.

**Comment by Piasy** [comment]
`v1.5.4.1` is released, please check [README](https://github.com/Piasy/BigImageViewer/blob/no-android-x/README.md) for setup instruction.
