### ISSUE TITLE
Forbidden 403

### ISSUE THREAD

**Issue by islomov** [Piasy/BigImageViewer#225]
Hi there

I cant build my project.

`Could not GET 'http://dl.bintray.com/piasy/maven/com/github/piasy/GlideImageLoader/1.5.7/GlideImageLoader-1.5.7.pom'. Received status code 403 from server: Forbidden
Disable Gradle 'offline mode' and sync project`

I tried with HTTPS and HTTP also. But it is not helping.

**Comment by Piasy** [comment]
Bintray is shutdown, please use latest version, and check latest README.
