### ISSUE TITLE
Some important zoom feature didn't find yet

### ISSUE THREAD

**Issue by superdiazzz** [Piasy/BigImageViewer#232]
Hi, thanks for this awesome library. I use this for my apps but, i think i need this kind of features.
1. After user zoom the image, the user click back button (or onBackPressed called) to return normal size (like first rendering)
2. Listener for zoom and also access foom event without pitch the screen. Suppose that i created button in corner with zoom in and zoom out i want that will be alternate of pitch zoom.

Sorry if i requested too much, but i think i didn't find these feateure yet.

**Comment by Piasy** [comment]
PR is welcome!
