### ISSUE TITLE
Failed to resolve: com.github.piasy:GlideImageLoader

### ISSUE THREAD

**Issue by DublikuntMux** [Piasy/BigImageViewer#239]
# Problem
When synchronizing a project with any version of the library.

# Gradle config

## Import Library
implementation 'com.github.piasy:BigImageViewer:1.8.1'
implementation 'com.github.piasy:GlideImageLoader:1.8.1'

## Connected repos
repositories {
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
}

**Comment by Piasy** [comment]
It works fine on my machine, so please check your network.
