### ISSUE TITLE
关于依赖此项目的问题

### ISSUE THREAD

**Issue by LitbLeo** [Piasy/BigImageViewer#25]
在我的项目中无法引用您的这个项目，不知道是什么情况？我的gradle版本是3.1的，用的也是classpath 'com.android.tools.build:gradle:2.2.2'这个版本，可是会报Error:Connection refused: connect

**Comment by Piasy** [comment]
你的网络出问题啦

**Comment by LitbLeo** [comment]
@Piasy 不会啊 我的网络是正常的，依赖其他项目都是可以的呀！不知道你这个需要什么特殊处理吗？

**Comment by Piasy** [comment]
这我就不清楚了啊，你看这个能不能访问？https://dl.bintray.com/piasy/maven/com/github/piasy/BigImageViewer/

**Comment by LitbLeo** [comment]
能的，方便加QQ么？

**Comment by LitbLeo** [comment]
你的依赖是放在项目目录最外层的build.gradle文件还是项目里面的那个？

**Comment by Piasy** [comment]
你看 https://github.com/Piasy/BigImageViewer/blob/master/app/build.gradle

**Comment by LitbLeo** [comment]
我看了  没毛病啊 你这个是依赖module嘛  我是直接
`allprojects {
    repositories {
        maven {
            url  "http://dl.bintray.com/piasy/maven"
        }
    }
}

// NOTE that the artifact id has been changed!
compile 'com.github.piasy:BigImageViewer:1.2.3'

// load with fresco
compile 'com.github.piasy:FrescoImageLoader:1.2.3'

// load with glide
compile 'com.github.piasy:GlideImageLoader:1.2.3'

// progress pie indicator
compile 'com.github.piasy:ProgressPieIndicator:1.2.3'`

这样就会有问题呀

**Comment by Piasy** [comment]
你贴一下你的根目录 build.gradle 和 app/build.gradle。

**Comment by LitbLeo** [comment]
这是app的
![image](https://cloud.githubusercontent.com/assets/5568469/21340580/8663c5a2-c6c2-11e6-8043-8d7167bec8f9.png)
这是build.gradle的
![image](https://cloud.githubusercontent.com/assets/5568469/21340599/a1aab0c8-c6c2-11e6-983c-3a719667dd2c.png)

**Comment by Piasy** [comment]
``` gradle
maven {
    url "http://dl.bintray.com/piasy/maven"
}
```

加在哪里了？

**Comment by LitbLeo** [comment]
原先放在build.gradle里面的，刚截图忘了加上去了

**Comment by Piasy** [comment]
@LitbLeo `200842165`，你可以加我 QQ

**Comment by Piasy** [comment]
@LitbLeo issue 我先关闭了，有问题随时 reopen
