### ISSUE TITLE
关于闪烁的问题

### ISSUE THREAD

**Issue by 447zyg** [Piasy/BigImageViewer#27]
关于缩略图加载完之后显示原图有一个非常明显的闪烁过程。
暂时没什么解决思路。。
想请教下大佬。@Piasy 

非常感谢。

**Comment by Piasy** [comment]
缩略图其实是显示在一个单独的 View 上的，能否做两个 View 的切换动效？

**Comment by 447zyg** [comment]
@Piasy  
抱歉早上才看到。。
 谢谢。
已改完。修改了BigImage的onFinish
不知道会不会写的太啰嗦了。如下0.0


    @WorkerThread
    @Override
    public void onFinish() {

        post(new Runnable() {
            @Override
            public void run() {
               
                AnimationSet set = new AnimationSet(true);
                AlphaAnimation animation = new AlphaAnimation(1, 0);
                animation.setDuration(500);
                animation.setFillAfter(true);
                set.addAnimation(animation);
                if (mThumbnailView != null) {
                    mThumbnailView.setAnimation(set);
                }

                if (mProgressIndicator != null) {
                    mProgressIndicator.onFinish();
                }

                if (mProgressIndicatorView != null) {
                    mProgressIndicatorView.setAnimation(set);
                }
                
                animation.setAnimationListener(new Animation.AnimationListener() {
                    @Override
                    public void onAnimationStart(Animation animation) {

                    }

                    @Override
                    public void onAnimationEnd(Animation animation) {
                        if (mThumbnailView != null) {
                            mThumbnailView.setVisibility(GONE);
                        }
                        if (mProgressIndicatorView != null) {
                            mProgressIndicatorView.setVisibility(GONE);
                        }
                    }

                    @Override
                    public void onAnimationRepeat(Animation animation) {

                    }
                });
            }
        });
    }

**Comment by Piasy** [comment]
我觉得没啥问题，你提一个 PR 吧 :)
