### ISSUE TITLE
没必要为了请求权限而加上RxJava和RxPermissions。

### ISSUE THREAD

**Issue by fanxxxx** [Piasy/BigImageViewer#28]
BigImageViewer加了rxjava 与 rxpermissions的依赖，作用仅仅是判断和请求一下存储时的权限。但我认为这个请求权限的动作不该由BigImageViewer这个框架来完成。仅仅为了一个权限加上了一个很大的rxjava2库。还会导致与其他使用rxjava1.x导致不兼容。

**Comment by Piasy** [comment]
你说得有道理。不过 RxJava 2.x 和 1.x 是不存在兼容性问题的。

**Comment by Piasy** [comment]
fixed by d85ded4ae0da44c4d0c3ef5f908dc62ff0694cbf
