### ISSUE TITLE
用Glide加载图片问题

### ISSUE THREAD

**Issue by Weststreet** [Piasy/BigImageViewer#29]
1.Callback会导致内存泄漏。
2.在图片未加载完成退出再次进入会长时间黑屏。

目前可以解决的办法：在退出fragment或者activity的时候调用Glide.clear(glideDownloadTarget);清除掉当前加载的target。

**Comment by Piasy** [comment]
Fresco 加载也存在同样的问题，在 view detach 时取消加载任务，可以解决这个问题，但具体能否取消、怎么取消，需要看一下 API。欢迎提交 pr！

**Comment by Piasy** [comment]
Memory leak: track #43.
Cancel action: track #36.
