### ISSUE TITLE
不支持旋转

### ISSUE THREAD

**Issue by 54binge** [Piasy/BigImageViewer#33]
ps：SubsamplingScaleImageView在viewpager中根据exif旋转会oom

**Comment by Piasy** [comment]
你的期望是什么？BIV 根据 exif 旋转 or not？还是 BIV 支持用户手动旋转，or 支持代码设置角度？

**Comment by 54binge** [comment]
对，根据exif信息旋转，我这边也是醉了，全是8M左右的大图，方向还都的根据exif来

2017年1月7日 12:03，"Piasy" <notifications@github.com>写道：

你的期望是什么？BIV 根据 exif 旋转 or not？还是 BIV 支持用户手动旋转，or 支持代码设置角度？

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Piasy/BigImageViewer/issues/33#issuecomment-271061070>,
or mute the thread

**Comment by Piasy** [comment]
了解了，SSIV 应该支持根据 exif 自动旋转，但你说会存在 OOM，我最近没有时间做这个，欢迎你深入一下，提交 pr :)

**Comment by Piasy** [comment]
Close this issue now, feel free to provide more information and reopen it.
