### ISSUE TITLE
放大至全屏后无法滑动

### ISSUE THREAD

**Issue by umeitime** [Piasy/BigImageViewer#34]
放大至全屏后上下无法滑动

**Comment by Piasy** [comment]
请提供一下机型信息，我并没有遇见过。

不过其实提供了我能做的也不多，最好还是你直接 clone 下来，调试一番，探查一下是什么原因。这个项目代码很少，结构也比较清晰，应该不麻烦 :)

**Comment by umeitime** [comment]
升级了1.2.7 发现还是原来的情况。

**Comment by Piasy** [comment]
Close this issue now, feel free to provide more information and reopen it.
