### ISSUE TITLE
cancel action?

### ISSUE THREAD

**Issue by KevinYaoooooo** [Piasy/BigImageViewer#36]
Please provide a cancel action, if image is not finish the loading, then user click back, it might produce some weird issue, so could you provide a cancel action for us, that we could use this method to cancel loading, cancel the callback or some... or even something important ** to release memory properly**

**Comment by Piasy** [comment]
Yeah, cancelation is important, but it should be done automatically, e.g. in `onDetachFromWindow`, but I'm too busy these days, you can find out how to cancel the Fresco/Glide image load request, and submit a pr :)

**Comment by Piasy** [comment]
Finally `v1.4.5` add a `cancel` method, and BIV will cancel image loading automatically when detach from window. Check it out :)
