### ISSUE TITLE
加载进度和缩略图显示问题

### ISSUE THREAD

**Issue by hss01248** [Piasy/BigImageViewer#40]
用的fresco,存在两个问题:
1.进度一直为0
2.设置了缩略图(网络,图片很小),本来应该是先很快加载缩略图,然后等了一会加载大图,但现在是空白页面等很长时间,然后缩略图闪过,然后立马就出来大图.

**Comment by Piasy** [comment]
PR is welcome!

**Comment by landsnail** [comment]
glide 加载缩略图一直有问题，没人遇到过吗？

**Comment by Piasy** [comment]
Fresco progress problem: track #10.
Thumbnail problem: feel free to open a new issue.
