### ISSUE TITLE
Can't set signature (Glide)

### ISSUE THREAD

**Issue by DennyWeinberg** [Piasy/BigImageViewer#44]
Before:
`Glide.with(mActivity).load(mediaItem.getUri())
        .skipMemoryCache(true)
        //.asBitmap()
        //.imageDecoder(new StreamBitmapDecoder(mActivity, DecodeFormat.PREFER_ARGB_8888))
        .thumbnail(0.4f)
        .dontAnimate()
        .signature(mediaItem.getSignature())
        .into(photoView);`

after:
`photoView.showImage(mediaItem.getUri());`

I need to set the signature because I edited my photo and need to reset the glide cache.

**Comment by steosoft** [comment]
@DennyWeinberg can you tell how you solved this issue?

**Comment by DennyWeinberg** [comment]
Did not found any no good solution for that. I still use glide with chrisbeans PhotoView.

**Comment by Piasy** [comment]
You can do something on the GlideImageLoader.

**Comment by steosoft** [comment]
@Piasy how to do that? I've tried to add in method
`public void loadImage(final Uri uri, final Callback callback)`
something like this:
`File file = new File(uri.getPath());`
and before `downloadOnly` add this:
`.signature(new StringSignature(_something_)`
but `.signature` and `downloadOnly` is not working together.. :(

**Comment by Piasy** [comment]
That's all about glide, maybe you can check out its docs.
