### ISSUE TITLE
请问如何添加请求头？比如Referer

### ISSUE THREAD

**Issue by jayleco** [Piasy/BigImageViewer#45]
由于有些带有防盗链的图片如果不带Referer将无法请求到真实的图片，我目前使用的是glide+SubsamplingScaleImageView，可以使用glide将图片下载到本地然后再将图片交给SubsamplingScaleImageView来显示，glide自带有添加header的方法所以很方便实现，但是您这个好像是直接使用图片地址请求图片，所以不知道glide+BigImageViewer应该怎么实现携带header请求

**Comment by Piasy** [comment]
无论是 Fresco 还是 Glide，都可以配置 OkHttpClient，有了这个之后，应该就可以为 HTTP 请求设置 header 了吧？

**Comment by jayleco** [comment]
就是说没法用glide自带的添加头信息的功能了是吧

**Comment by Piasy** [comment]
对的，或者你实现一个自定义的 GlideLoader，这样就可以满足你的任意需求了。
