### ISSUE TITLE
Request Features Callbacks

### ISSUE THREAD

**Issue by webserveis** [Piasy/BigImageViewer#49]
I try to controller view states image resources... I need capture events

Please add Callbacks support in future:

OnRequestImageSuccesfull -> when donwload image.
OnRequestImageError -> when error download image.
OnRequestImageCache -> when image is retrieve cache.
OnRequestImageCacheError -> when image poblem retieve cache.

**Comment by Piasy** [comment]
Great idea! But I'm sorry that I'm too busy for that, could you please submit a PR? thanks!

**Comment by Piasy** [comment]
Added via #50
