### ISSUE TITLE
gif support?

### ISSUE THREAD

**Issue by umeitime** [Piasy/BigImageViewer#5]
如果是用Fresco加载图片？

**Comment by Piasy** [comment]
可以考虑作为一个 feature，但如果播放 gif，就不能缩放了。

**Comment by yayaxiong** [comment]
目前我是这样使用的，先判断是不是长图，是长图就使用 BigImageView 加载，不是长图就使用 PhotoDraweeView 加载，这样就可以加载 gif 而且 可以缩放

**Comment by Piasy** [comment]
@yayaxiong 你应该检查是不是大图，也就是尺寸。photo drawee view加载大图内存占用很高，很卡。

**Comment by yayaxiong** [comment]
@Piasy photo drawee view的确是占用内存，目前我请求图片的时候都是带上宽高进行resize，控制还比较好，最好的还是你的 bigView

**Comment by Piasy** [comment]
@yayaxiong 嗯，如果不需要支持缩放和移动，利用服务端的图片处理服务，直接请求小图+fresco 就够了。但如果要支持缩放和移动，那还是 SSIV 更省内存。

**Comment by umeitime** [comment]
GIF图片就正常加载 不缩放好了。

**Comment by Paul1121** [comment]
请问用FrescoImageLoader应该可以显示gif动态图吧，具体怎么做？

**Comment by Piasy** [comment]
FrescoImageLoader 只负责加载，并不负责显示，现在显示都是  SSIV

**Comment by ervinod** [comment]
Hello....
Have you added gif picture support ? or this enhancement is still pending....

**Comment by Piasy** [comment]
Still pending :(

**Comment by ervinod** [comment]
can you please suggest any alternative to display gif image ......

**Comment by ParkerK** [comment]
@ervinod SSIV doesn't support animated GIFs, and this library uses SSIV

**Comment by Piasy** [comment]
Gif support is added since v1.5.0, check it out 🍻🍻🍻
