### ISSUE TITLE
Custom Subsampling Scale Image View

### ISSUE THREAD

**Issue by HR** [Piasy/BigImageViewer#51]
Allow setting/initialising with a custom Subsampling Scale Image View
Any ideas on how to implement this?

**Comment by Piasy** [comment]
Why do we need this?

**Comment by HR** [comment]
I need to override SubsamplingScaleImageView's `protected void onSizeChanged(int w, int h, int oldw, int oldh)` method in order to change its default device orientation behaviour (which [flawed in some situations](https://github.com/davemorrissey/subsampling-scale-image-view/issues/155))

**Comment by Piasy** [comment]
I think we can add a `setSSIV` method to `BigImageView`, which will add the provided SSIV as its first child, then we can add a `useExternalSSIV` attribute(boolean), which means it should not create a SSIV itself. Waiting for your PR :)

**Comment by HR** [comment]
OK but what about the AttributeSet (i.e. `attr` at init) required by the custom Subsampling Scale Image View to initialise since its constructor is `SubsamplingScaleImageView(Context context, AttributeSet attr)`?

**Comment by Piasy** [comment]
Oh I got it, as `BigImageView` is a `FrameLayout`, maybe we could just declare a custom SSIV in layout xml file, then we only need `useExternalSSIV` attribute(maybe name it `useXmlSSIV` is better), please try that.

**Comment by HR** [comment]
I'm not sure how that would solve the problem since I require a CustomSubsamplingScaleImageView _class_ not _resource_.

**Comment by Piasy** [comment]
Declare it in layout xml file, use it as SSIV instance needed by BIV.

**Comment by HR** [comment]
So use it like
```java
CustomSSIV customSSIV =
 (CustomSSIV) findViewById(R.id.CustomSSIView);
BigImageView bigImageView = new BigImageView();
bigImageView.setSSIV(customSSIV);
bigImageView.showImage(Uri.parse(url));

```

**Comment by Piasy** [comment]
No, `findViewById` call should happen in BIV constructor, and also we don't need an extra boolean attribute. If we find a SSIV, then use it, else we new a SSIV.

**Comment by HR** [comment]
Then how would you pass your custom SSIV class to BigImageView ?

**Comment by Piasy** [comment]
With my last comment, we've already done.

**Comment by HR** [comment]
I'm still not sure how you would specify a custom SSIV _class_ since what you seem to be talking about is a custom SSIV _layout_

Can you please provide a example to clarify things?

**Comment by Piasy** [comment]
See [this commit](https://github.com/Piasy/BigImageViewer/commit/c54d067d5d700ca99885c049dad9863d8fae336b) :)

**Comment by HR** [comment]
Awesome! It works. Can you please merge and release ASAP?

**Comment by Piasy** [comment]
Sure :)

**Comment by Piasy** [comment]
Checkout v1.3.1
