### ISSUE TITLE
how to show gif picture

### ISSUE THREAD

**Issue by Paul1121** [Piasy/BigImageViewer#54]
how to show gif picture

**Comment by Piasy** [comment]
SSIV doesn't support gif

**Comment by Paul1121** [comment]
不用SSIV呢？

**Comment by Paul1121** [comment]
使用FrescoImageLoader加载，Fresco是支持加载gif图片的，
Uri uri; 
DraweeController controller = Fresco.newDraweeControllerBuilder() 
.setUri(uri) 
.setAutoPlayAnimations(true) 
. // 其他设置（如果有的话） 
.build(); 
mSimpleDraweeView.setController(controller);

**Comment by Paul1121** [comment]
能不能支持gif，不要缩放这些，不能支持的话就算了

**Comment by Piasy** [comment]
Track #5

**Comment by Paul1121** [comment]
干嘛关了问题？

**Comment by Piasy** [comment]
As I said, track #5.
