### ISSUE TITLE
BigImageView is leaking Memory

### ISSUE THREAD

**Issue by CeJienAJPC** [Piasy/BigImageViewer#56]
I am initializing BigImageViewer with
`BigImageViewer.initialize(GlideImageLoader.with(getActivity().getApplicationContext()));`

According to LeakCanary, the `com.github.piasy.biv.view.BigImageView.mContext` is leaking memory.

Any Ideas?

Thanks.

**Comment by Piasy** [comment]
Sorry that I don't have enough time to dig into this issue, please do some debug... And maybe this issue is helpful: #43

**Comment by Piasy** [comment]
Track #43
