### ISSUE TITLE
长图打开之后没有放大展示

### ISSUE THREAD

**Issue by Aplombs** [Piasy/BigImageViewer#57]

**Comment by Piasy** [comment]
需要设置 `optimizeDisplay` 属性为 true。

**Comment by Aplombs** [comment]
好的，多谢！回头我试试！！
            在2017年07月16日 10:33，Piasy 写道： 需要设置 optimizeDisplay 属性为 true。

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Piasy/BigImageViewer","title":"Piasy/BigImageViewer","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Piasy/BigImageViewer"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Piasy in #57: 需要设置 `optimizeDisplay` 属性为 true。"}],"action":{"name":"View Issue","url":"https://github.com/Piasy/BigImageViewer/issues/57#issuecomment-315577175"}}}
