### ISSUE TITLE
Lost OkHttpImagePipeline

### ISSUE THREAD

**Issue by blink7** [Piasy/BigImageViewer#62]
In my app I use OkHttpImagePipeline instead of standard one, but BigImageViewer breaks this configuration and returns everything to default. How to prevent it?

**Comment by Piasy** [comment]
It's just showcase how to use this library, if we don't initialize it in `FrescoLoaderActivity`, and start it at first, what will happen?

**Comment by blink7** [comment]
You mean start the app without `BigImageViewer.initialize()`?

**Comment by Piasy** [comment]
I mean start the **activity** without `BigImageViewer.initialize(...)`.

**Comment by blink7** [comment]
Then I get `InflateException` from XML like [this](https://github.com/Piasy/BigImageViewer/issues/61)...

**Comment by Piasy** [comment]
Well, actually, my first comment is not a question for myself, it's a question for you, and if we don't initialize BIV, of course it will crash.

**Comment by blink7** [comment]
But using Fresco I'm already initializing it. Or is it just in case for those who do not?

**Comment by Piasy** [comment]
Use case 1: open `FrescoLoaderActivity` first, then open `GlideLoaderActivity`.

Use case 2: Open `GlideLoaderActivity` only.

**Comment by blink7** [comment]
Ok, I get it.

Last question: can I change duration of double tap animation and scale ratio after double tap?

**Comment by Piasy** [comment]
That could be found out from SSIV.
