### ISSUE TITLE
Load Image from Inputstream

### ISSUE THREAD

**Issue by sethchhim** [Piasy/BigImageViewer#63]
Does this library support loading image from an inputstream?

My use case is loading an image from a compressed archive without writing to disk. Thank you for any recommendations.

**Comment by Piasy** [comment]
It seems SSIV doesn't support that feature.

But if you don't want to write the decompressed image into disk, would you hold it in memory? If so, that's actually what we wan't to avoid, because it will eat a lot of memory.

If your image is very small, BIV has no advantage.
