### ISSUE TITLE
How to make it work with glide 4

### ISSUE THREAD

**Issue by Rajeshr34** [Piasy/BigImageViewer#64]
As in title can you update or guide plz?

**Comment by Piasy** [comment]
Doesn't glide 4.x compatible with 3.x? If not, pr is welcome!

**Comment by dfreniche** [comment]
Confirmed here: not working with 4.x
Don't know how to fix, sadly...

**Comment by Piasy** [comment]
fixed by #68

**Comment by Piasy** [comment]
`v1.4.0` is published, check it out :)
