### ISSUE TITLE
[enhancement] Disable Pinch to Zoom

### ISSUE THREAD

**Issue by ryanzor** [Piasy/BigImageViewer#67]
(sorry if this already exists)

I have a use case that I just want to display a very large image without downsampling but do not want the user to be able to zoom on the image.  Is this currently possible?  Any plans to add this or willingness to accept a pr with the change?

**Comment by Piasy** [comment]
You can get SSIV object with `getSSIV `, then use SSIV's API.

**Comment by ryanzor** [comment]
Perfect!  Thanks again for the fast responses!
