### ISSUE TITLE
Error: Could not find com.github.piasy:BigImageViewer:1.2.0.

### ISSUE THREAD

**Issue by crysan** [Piasy/BigImageViewer#7]
Hi!

```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:25.0.1'
    compile 'com.android.support:design:25.0.1'

    compile 'com.github.piasy:BigImageViewer:1.2.0'
}
```
```
allprojects {
    repositories {
        jcenter()
        mavenCentral()
        maven { url "https://www.jitpack.io" }
    }
}
```
Result:
```
Error:Could not find com.github.piasy:BigImageViewer:1.2.0.
Required by:
    MyLevel:app:unspecified
<a href="searchInBuildFiles">Search in build.gradle files</a>
```

**Comment by Piasy** [comment]
It should be available in jcenter. 

But you can try to add `maven { url  "http://dl.bintray.com/piasy/maven" }` into your root project build.gradle.

**Comment by crysan** [comment]
Yes!
Ty!

**Comment by crysan** [comment]
And error:
`android.view.InflateException: Binary XML file line #6: Binary XML file line #6: Error inflating class com.github.piasy.biv.BigImageView`

```
    <com.github.piasy.biv.BigImageView
        android:id="@+id/mBigImage"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />
```

**Comment by Piasy** [comment]
@crysan the package name has been changed into `com.github.piasy.biv.view.BigImageView`, sorry that I haven't updated README in time.

**Comment by crysan** [comment]
Ok. It works.

Now
`android:src="@drawable/start_wallpaper"`
not works?

**Comment by Piasy** [comment]
Yes, use `showImage`.

**Comment by crysan** [comment]
Ok. Ty!

**Comment by LeTuanVu-Dev** [comment]
android.view.InflateException: Binary XML file line #6: Binary XML file line #6: Error inflating class com.github.piasy.biv.BigImageView 
this error is still bad at
