### ISSUE TITLE
Disable tap to retry fail image

### ISSUE THREAD

**Issue by thakkaryash94** [Piasy/BigImageViewer#72]
I am using `setOnClickListener` on BigImageView. It will trigger click listener fine if I load image from local but if I load online image and it fails to load, then click listener is not working because it is actually trying to load the image again instead of triggering click listener.

When I walk through the code, I think [this line](https://github.com/Piasy/BigImageViewer/blob/master/BigImageViewer/src/main/java/com/github/piasy/biv/view/BigImageView.java#L290) is causing problem. For normal use case it is fine but I think there must an option to disable retry on image click so that user can listen to it.

Or If I am wrong then guide me how to implement onclick for failure image use case.

Currently I achieved this by `ImageLoader.Callback` and override `onFail` function.

**Comment by Piasy** [comment]
I think maybe we could intercept the click event, and forward it out to user's listener. Could you please submit a pr?

**Comment by thakkaryash94** [comment]
I think we should remove click event for failure image case. [here](https://github.com/Piasy/BigImageViewer/blob/master/BigImageViewer/src/main/java/com/github/piasy/biv/view/BigImageView.java#L290)

We should leave it on user how they want to retry. We already have ImageLoader to catch image load fail case. then we just need to add `mFailureImageView.setOnClickListener(listener);` on `setOnClickListener` [here](https://github.com/Piasy/BigImageViewer/blob/master/BigImageViewer/src/main/java/com/github/piasy/biv/view/BigImageView.java#L164) and everything will work fine.

**Comment by Piasy** [comment]
That require extra effort to implement tap to retry, I prefer add `mFailureImageView.setOnClickListener(listener);` in `setOnClickListener` method, but automatically retry.

**Comment by thakkaryash94** [comment]
I think I solved the problem without much refactoring. I added one boolean attribute `tapToRetry`. By default it will be true or user can switch to false manually. If it is true then our `showImage()` inbuilt `setOnClickListener` [here](https://github.com/Piasy/BigImageViewer/blob/master/BigImageViewer/src/main/java/com/github/piasy/biv/view/BigImageView.java#L290) will listen or if it is false then global `setOnClickListener` will listen with tapToRetry false condition like below.
```
    @Override
    public void setOnClickListener(OnClickListener listener) {
        mImageView.setOnClickListener(listener);
        if(!mTapToRetry) {
            mFailureImageView.setOnClickListener(listener);
        }
    }
```
I think currently we can go with this approach. I already tested on device, It is working as aspect. If you say, I can submit a PR.

**Comment by Piasy** [comment]
How about this commit: 65e21dfd4bd1d6886ba49e664ae3ece690fa3068

**Comment by thakkaryash94** [comment]
But what if I don't want to retry on click? With above commit, it will fire both - retry and click.
Actually, I am asking this because I am using FragmentStatePagerAdapter with Viewpager for fullscreen imageview and on imageview click, I show and hide toolbar(Immersive Mode). So it will look odd if if user click on fail image and internet is still off, imageview will blink with toolbar animation.

How about [this](https://github.com/thakkaryash94/BigImageViewer/commit/94e2353cb52cdaa6145e636a99eab7759ba0c64d). I combined both code.

**Comment by Piasy** [comment]
Could you please update your pr ( #73 ) directly? Then we can start review code :)

**Comment by thakkaryash94** [comment]
Done.

**Comment by thakkaryash94** [comment]
fixed. https://github.com/Piasy/BigImageViewer/commit/6467c628f68046c03bc43d181fd47f70da4db992

**Comment by Piasy** [comment]
v1.4.3 is released, forgive my bad network status :(
