### ISSUE TITLE
Unauthorized 401 when trying to access three libraries

### ISSUE THREAD

**Issue by HoratiuVezentan** [Piasy/BigImageViewer#79]
Hi,
I'm trying to access the latest version(v1.4.5) of three libraries, BigImageViewer, GlideImageLoader and ProgressPieIndicator; on debug mode i'm getting errors for each library like this one:
"Error:org.gradle.api.resources.ResourceException: Could not get resource 'https://jitpack.io/com/github/piasy/GlideImageLoader/1.4.5/GlideImageLoader-1.4.5.pom'.
Error:org.gradle.api.UncheckedIOException: Could not HEAD 'https://jitpack.io/com/github/piasy/GlideImageLoader/1.3.2/GlideImageLoader-1.4.5.pom'. Received status code 401 from server: Unauthorized".

Now i have the same problem on older versions.

**Comment by Piasy** [comment]
This library is hosted on bintray, please add this to your root `build.gradle` file:

``` gradle
allprojects {
    repositories {
        maven {
            url  "http://dl.bintray.com/piasy/maven"
        }
    }
}
```

**Comment by HoratiuVezentan** [comment]
I already have this code into build.gradle file. This is how the allprojects section looks:

`allprojects {
    repositories {
        jcenter()

        maven { url 'https://maven.google.com'}
        maven { url "https://jitpack.io"}
        maven {
            url  "http://dl.bintray.com/piasy/maven"
        }

        google()
    }
}`

**Comment by Piasy** [comment]
move `http://dl.bintray.com/piasy/maven` to the top of them.

**Comment by HoratiuVezentan** [comment]
Done. That was the issue. Thank you!

**Comment by charlag** [comment]
Hey, sorry for necroposting but it doesn't help me:
```groovy
buildscript {
    ext.kotlin_version = '1.3.72'
    repositories {
        maven {
            url "http://dl.bintray.com/piasy/maven"
        }
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.0.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://jitpack.io" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

```
* What went wrong:
Could not determine the dependencies of task ':app:compileBlueReleaseKotlin'.
> Could not resolve all files for configuration ':app:greenDebugRuntimeClasspath'.
   > Could not resolve com.github.piasy:GlideImageLoader:1.6.5.
     Required by:
         project :app
      > Could not resolve com.github.piasy:GlideImageLoader:1.6.5.
         > Could not get resource 'https://jitpack.io/com/github/piasy/GlideImageLoader/1.6.5/GlideImageLoader-1.6.5.pom'.
            > Could not GET 'https://jitpack.io/com/github/piasy/GlideImageLoader/1.6.5/GlideImageLoader-1.6.5.pom'. Received status code 401 from server: Unauthorized

```

**Comment by charlag** [comment]
Oof, sorry I've added it to the buildscript instead
