### ISSUE TITLE
Double click zoom does not work well

### ISSUE THREAD

**Issue by mustafakuloglu** [Piasy/BigImageViewer#86]
Hi @Piasy 

Double click only filling screen. If the photo is already filling screen, it does not do anything.  But expected is zoom.

**Comment by Piasy** [comment]
I think that's because the image is too small, and SSIV have max scale ratio, can you try a larger image?

**Comment by mustafakuloglu** [comment]
I tried with a bigger picture. Result is the same. Two finger zoom is working. But double click is not working. I am trying with this app https://play.google.com/store/apps/details?id=com.generalmobile.app.gallery  .

**Comment by Piasy** [comment]
Could you please try the demo? I've tried it on Nexus 5X, it works well.

**Comment by mustafakuloglu** [comment]
The issue abaut optimizeDisplay="false". I think it's an optimization of memory. So i made yes. But on your example code this value is false. I say yes and try and it is working very well. Thanks for support.
