### ISSUE TITLE
FrescoImageLoader 1.4.6 failed to resolve error

### ISSUE THREAD

**Issue by DominList** [Piasy/BigImageViewer#87]
It looks like gradle cannot find the link to FrescoImageLoader 1.4.6:
`Error:(57, 13) Failed to resolve: com.github.piasy:FrescoImageLoader:1.4.6`

**Comment by Piasy** [comment]
Please add this to your top level build.gradle:

``` gradle
allprojects {
    repositories {
        maven {
            url  "http://dl.bintray.com/piasy/maven"
        }
    }
}
```

**Comment by DominList** [comment]
I've already had it.

**Comment by Piasy** [comment]
I find out it wasn't uploaded last time, I've fixed that, please try again.
