### ISSUE TITLE
GlideImageLoader-1.4.6.pom. Received status code 401 from server: Unauthorized

### ISSUE THREAD

**Issue by TheStar4Fate** [Piasy/BigImageViewer#88]
Error:org.gradle.internal.resource.transport.http.HttpErrorStatusCodeException: Could not HEAD 'https://jitpack.io/com/github/piasy/GlideImageLoader/1.4.6/GlideImageLoader-1.4.6.pom'. Received status code 401 from server: Unauthorized
![qq 20180201150525](https://user-images.githubusercontent.com/7358871/35665498-79e1647a-0761-11e8-9580-57b1b08dad5a.png)

**Comment by Piasy** [comment]
This library hosts on bintray, not jitpack, please put bintray at the top of your repository:

``` gradle
allprojects {
    repositories {
        maven {
            url  "http://dl.bintray.com/piasy/maven"
        }
    }
}
```

**Comment by TheStar4Fate** [comment]
我添加了，但还是有这个问题

**Comment by Piasy** [comment]
Put it at the first place.

**Comment by TheStar4Fate** [comment]
好了，问题已解决
