### ISSUE TITLE
Thumbnail not works!

### ISSUE THREAD

**Issue by Omid3d** [Piasy/BigImageViewer#89]
Hello 
Thanks for your great library and supporting libraries like glide and picasso.

I have a problem with your library.
When I call showImage method, the first parameter is thumbnail. Then I expect to see thumbnail before loading big image, but this does not work. Also the progressPieIndicator not shown as well.
Here is my code to initialize and show image:
```
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        BigImageViewer.initialize(GlideImageLoader.with(getApplicationContext(), getCustomOkHttpClient()));

        setContentView(R.layout.app_bar_activity_image_viewer);

        bivContainer = findViewById(R.id.bIVContainer);
        bivContainer.setProgressIndicator(new ProgressPieIndicator());
        bivContainer.showImage(thumbUri, uri);
    }
```

layout part: 
```
...
    <com.github.piasy.biv.view.BigImageView
        android:id="@+id/bIVContainer"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:failureImage="@drawable/ic_broken_image_white_48dp"
        app:failureImageInitScaleType="fitCenter"
        app:initScaleType="centerInside"
        app:optimizeDisplay="true"/>
...

```
I looked in GlideImageLoader class and It seems you never call onDownloadStart of  ImageDownloadTarget defined in loadImage method, so callback.onStart won't call and finally onStart that implemented in BigImageView won't call to load thumbnail image. 
Is there anything that I forgot to implement in my code?

Reference link:
https://github.com/Piasy/BigImageViewer/blob/1fbf8abd26a5c700ae00373b60be35e4afdaaac4/GlideImageLoader/src/main/java/com/github/piasy/biv/loader/glide/GlideImageLoader.java#L88-L90

**Comment by Piasy** [comment]
It's called here:

https://github.com/Piasy/BigImageViewer/blob/master/GlideImageLoader/src/main/java/com/github/piasy/biv/loader/glide/GlideProgressSupport.java#L124

Actually I test it in GlideLoaderActivity, and it works in my phone, although the thumbnail disappeared very quickly because the big image is loaded very quickly. Could you please try another image and thumbnail?

**Comment by Omid3d** [comment]
I'm sorry for late reply.
Finally I found the solution
thanks for pointed out the line where onDownloadStart called.
the problem comes from url comparing in following lines:
https://github.com/Piasy/BigImageViewer/blob/1fbf8abd26a5c700ae00373b60be35e4afdaaac4/GlideImageLoader/src/main/java/com/github/piasy/biv/loader/glide/GlideProgressSupport.java#L113-L116
there is two urls in these lines:
1- Url in update method parameter that comes from okhttp interceptor.
2- Url in LISTENERS map that comes from glide ImageDownloadTarget

Now library tries to match 1 as key with 2 in map but actually my url builder passed to okhttp had a port number (80) in address, but image url I passed to BigImageViewer.showImage did not have that port number in address. So simple string comparing failed because of this extra port number in one of addresses and no listener found and thumbnail image won't show with progress bar.
When I build exactly a same url for image with my okhttp url the problem solved.
Maybe you need to check these scenarios in url comparing or maybe that was my OOP mistake.

Thanks for your support and this great library.
