### ISSUE TITLE
 Binary XML file line #0: Binary XML file line #0: Error inflating class com.github.piasy.biv.view.BigImageView 

### ISSUE THREAD

**Issue by amodkanthe** [Piasy/BigImageViewer#92]
Getting issue     android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class com.github.piasy.biv.view.BigImageView when using it 

Try creating sample app

and use
` maven {
            url  "http://dl.bintray.com/piasy/maven"
        }`
     compile 'com.github.piasy:GlideImageLoader:1.4.6'
    compile 'com.github.piasy:BigImageViewer:1.4.6'
    compile 'com.github.piasy:ProgressPieIndicator:1.4.6'

`<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="android.hackernewsak.com.myapplication.MainActivity">

    <com.github.piasy.biv.view.BigImageView xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:id="@+id/mBigImage"
        android:layout_width="match_parent"
        android:layout_height="200dp"
        app:optimizeDisplay="false"
        app:failureImageInitScaleType="center" />

</android.support.constraint.ConstraintLayout>`

`BigImageViewer.initialize(GlideImageLoader.with(getContext()));
        BigImageView bigImageView = view.findViewById(R.id.mBigImage);
        bigImageView.setProgressIndicator(new ProgressPieIndicator());
        bigImageView.showImage(
                Uri.parse("sone url"));`

**Comment by Piasy** [comment]
Could you please try the demo app?

**Comment by amodkanthe** [comment]
implementation project(':BigImageViewer') is what you are using in demo app.
It is failing when using 

compile 'com.github.piasy:GlideImageLoader:1.4.6'
compile 'com.github.piasy:BigImageViewer:1.4.6'
compile 'com.github.piasy:ProgressPieIndicator:1.4.6'

**Comment by amodkanthe** [comment]
Could you please try using this

compile 'com.github.piasy:GlideImageLoader:1.4.6'
compile 'com.github.piasy:BigImageViewer:1.4.6'
compile 'com.github.piasy:ProgressPieIndicator:1.4.6'

**Comment by Piasy** [comment]
I mean, could you please clone this project, and run the `app` module of this project.

**Comment by amodkanthe** [comment]
yeah that is working as I said it is not working when I am using 

compile 'com.github.piasy:GlideImageLoader:1.4.6'
compile 'com.github.piasy:BigImageViewer:1.4.6'
compile 'com.github.piasy:ProgressPieIndicator:1.4.6'

**Comment by Piasy** [comment]
Then there must be some difference between your code and sample code, using the source code (through `project(':BigImageViewer')`) or the published aar (through `'com.github.piasy:GlideImageLoader:1.4.6'`) should be the same.

**Comment by amodkanthe** [comment]
there is no change in code just this difference can you please check

**Comment by Piasy** [comment]
Any update? @amodkanthe

**Comment by Piasy** [comment]
I'm going to close this issue, feel free to reopen it :)
