### ISSUE TITLE
Programmatically zoom

### ISSUE THREAD

**Issue by NickRimmer** [Piasy/BigImageViewer#94]
Hi! Thank you for you greate job!
How can I set image scale on start, before show, with custom center position?

**Comment by Piasy** [comment]
I think you could call `getSSIV`, then use SSIV API on it.

**Comment by NickRimmer** [comment]
I got some troubles with it, like "can't get method from null..." or something like this. I can show you the error later.

**Comment by Piasy** [comment]
When do you call it? If you don't use custom SSIV, `getSSIV` should be available after BIV's constructor. Or maybe your BIV is null? then that's the problem of your code :)

**Comment by NickRimmer** [comment]
This is my code (kotlin), and before I made "BigImageViewer.initialize(FrescoImageLoader.with...":

        bigImageView.setProgressIndicator(ProgressPieIndicator())
        bigImageView.setImageLoaderCallback(object: ImageLoader.Callback {
            override fun onSuccess(image: File?) {
                bigImageView.ssiv
                        .animateScaleAndCenter(3f, bigImageView.ssiv.center)
                        .start()
            }

            override fun onFinish() {}
            override fun onFail(error: Exception?) {}
            override fun onCacheHit(image: File?) {}
            override fun onCacheMiss(image: File?) {}
            override fun onProgress(progress: Int) {}
            override fun onStart() {}
        })

        bigImageView.showImage(Uri.parse(Globals.GetUrlServer() + "files/map.jpg"))

Without "bigImageView.ssiv.animateScaleAndCenter(3f, bigImageView.ssiv.center).start()" it's working fine.

And this is error:

> Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$AnimationBuilder.start()' on a null object reference

**Comment by Piasy** [comment]
Please figure it out what is null? `bigImageView`? `bigImageView.ssiv`? or `bigImageView.ssiv.animateScaleAndCenter(3f, bigImageView.ssiv.center)`?

**Comment by NickRimmer** [comment]
if(bigImageView==null) throw Error("bigImageView is empty")

        bigImageView.setImageLoaderCallback(object: ImageLoader.Callback {
            override fun onSuccess(image: File?) {

                if(bigImageView.ssiv==null) throw Error("SSIV is empty")

                val op = bigImageView.ssiv
                        .animateScaleAndCenter(3f, bigImageView.ssiv.center)
                        ?: throw Error("animateScaleAndCenter is empty")

                op.start()

            }

            //region unused
            override fun onFinish() {}
            override fun onFail(error: Exception?) {}
            override fun onCacheHit(image: File?) {}
            override fun onCacheMiss(image: File?) {}
            override fun onProgress(progress: Int) {}
            override fun onStart() {}
            //endregion
        })

        bigImageView.showImage(Uri.parse(Globals.GetUrlServer() + "files/map.jpg"))

> Caused by: java.lang.Error: animateScaleAndCenter is empty

**Comment by Piasy** [comment]
So that seems to be the problem of BIV. Could you please debug it?

**Comment by Piasy** [comment]
Any update?

**Comment by Piasy** [comment]
Going to close it for now, feel free to reopen it.
