### ISSUE TITLE
Wrong Orientation on images

### ISSUE THREAD

**Issue by unlemci** [Piasy/BigImageViewer#95]
BigImageView shows some image with wrong orientation from path; so i have got a solution for this;
Add this util https://gist.github.com/9re/1990019
After when you are showing bitmap, use this code `ExifUtil.Companion.rotateBitmap(imagePath, bitmap);` for showing right orientation

I don't want to edit this library on my project :+1:

**Comment by Piasy** [comment]
BIV doesn't operate on Bitmap directly, so maybe you should open this issue in SSIV repo?

**Comment by unlemci** [comment]
I opened an issue on that repo https://github.com/davemorrissey/subsampling-scale-image-view/issues/407

**Comment by unlemci** [comment]
@Piasy maybe you should to look that subject?

**Comment by unlemci** [comment]
I think this problem is about BigImageView doesn't use correct orientation about subsampling scale image view library.

In this issue davemorrissey/subsampling-scale-image-view#407 he says look to wiki about this.

We don't use that library BigImageView uses...

**Comment by Piasy** [comment]
As that wiki said:

> Images stored in resources and assets cannot be rotated based on EXIF, you'll need to do it manually. You probably know the orientation of your own files :-)

So maybe we need to read the orientation from image file, then call `ssiv. setOrientation`.

PR is welcome!

**Comment by unlemci** [comment]
Am i need to do something to fix this?
