### ISSUE TITLE
Use with Glide custom ModelLoader

### ISSUE THREAD

**Issue by jordaneckhardt** [Piasy/BigImageViewer#96]
Hey, thanks for creating this! It's super helpful for loading big images.

Unfortunately, I'm not sure if I can use BigImageViewer to load encrypted images. I'm successfully loading encrypted images using Glide with a custom ModelLoader that decrypts the images during Glide's decoding step, but these images are not large enough that I need to use BigImageViewer. In a separate view in my app, I'm displaying images that can be quite large, so I'm hoping to use BigImageViewer to display them. All images in my app must be encrypted on disk.

Is it possible to use BigImageViewer with a GlideImageLoader that uses a custom ModelLoader? If not, could you think of any other way I could decrypt image files while presenting them using BigImageViewer?

**Comment by Piasy** [comment]
Of course you can, you can implement a custom `ImageLoader`, then do the decryption work, then send the decrypted file path through `ImageLoader.Callbacl.onSuccess` callback, then it will display the decrypted image.

**Comment by jordaneckhardt** [comment]
Thanks for your answer! I'd actually like to decrypt the image without ever saving a decrypted file. This way I can avoid ever saving decrypted data in the filesystem. Is this possible? ImageLoader.Callbacl.onSuccess() accepts a File object...

**Comment by Piasy** [comment]
I don't know whether SSIV can receive output stream, could you please check it out? If it can, then we can create another `onSuccess` callback that handle it to SSIV.

**Comment by jordaneckhardt** [comment]
It looks like SSIV accepts an `ImageSource`, which requires a URI: http://davemorrissey.github.io/subsampling-scale-image-view/javadoc/

That said, SSIV does provide the method `setBitmapDecoderFactory()` to override the default decoder. Perhaps a custom implementation of `ImageDecoder` with a `decode()` method that creates a `Bitmap` from an output stream instead of from a URI could be the answer...

**Comment by Piasy** [comment]
Yes, but please note that you need implement subsampling when create Bitmap, otherwise, memory sucks.

**Comment by Piasy** [comment]
Close this issue now, feel free to reopen it for further question.

**Comment by sandy-8925** [comment]
I am also interested in using BigImageView with Glide, using a custom ModelLoader.

It might be easy to implement this, by modifying GlideImageLoader class to move the mRequestManager load calls in GlideImageLoader.loadImage() and GlideImageLoader.prefetch()
 into some different function, and we can then create a subclass of GlideImageLoader and override the load calls. We can then initialize BigImageViewer with our subclass.

Move the following in GlideImageLoader.loadImage()
```
mRequestManager
                .downloadOnly()
                .load(uri)
                .into(target);
```
into a non-final protected function loadImageThroughGlide(RequestManager, Uri, Target)

and change the following in GlideImageLoader.prefetch()
```
mRequestManager
                .downloadOnly()
                .load(uri)
                .into(new SimpleTarget<File>() {
                    @Override
                    public void onResourceReady(File resource,
                            Transition<? super File> transition) {
                        // not interested in result
                    }
                });
```

to a call to loadImageThroughGlide(RequestManager, Uri, Target) (just pass that SimpleTarget instance as the third parameter)

**Comment by sandy-8925** [comment]
I think we might not need (or be able to use) the RequestManager parameter. I think we need to use GlideApp.with(context) in order for our custom ModelLoader to get picked up. Will test it out and see if that's the case.

**Comment by Piasy** [comment]
@sandy-8925 There is a PR #120 , maybe it's what you want?

**Comment by Piasy** [comment]
v1.5.2 support custom glide components, check it out!

**Comment by sandy-8925** [comment]
Awesome, thanks!
