### ISSUE TITLE
More control over BigImageView for Transition animation

### ISSUE THREAD

**Issue by KirkBushman** [Piasy/BigImageViewer#98]
Hi,
I'm trying to implement a shared element transition in between two activities ending in a BigImageView.
Since loading the source image could take long I'm using the thumbnail image, but I notice that sometimes the image does't transition right, because the View switches from thumbnail to source.

Can we have the possibility to switch on command, to wait for the animation to end? 

On a second note, since I'm using Glide, and the thumbnail appears in my app before, I have it cached already: Can we have the ability to use a custom RequestManager call for the thumbnail?

Thanks in advance

**Comment by Piasy** [comment]
You mean a callback live `onImageLoaded`? You can try `setImageLoaderCallback`.

To use a custom RequestManager, you can implement your own GlideImageLoader.

**Comment by KirkBushman** [comment]
I created my own GlideImageLoader, with a custom RequestManager, and that worked.
But I don't see in ImageLoader.Callback, the possibility to switch from thumbnail to source image at will.
Am I missing something?

**Comment by Piasy** [comment]
Oh yes, there is no callback of "switch from thumbnail to source image", but PR is welcome :)

**Comment by KirkBushman** [comment]
allright, PRs it is...

**Comment by KirkBushman** [comment]
I'm starting to work on this, I'll allow the image to keep the thumbnail for a delay, while the animation finishes, and only later set the full image... 
I've created a PR with some groundwork fixes, tell me what you think beforehand.

**Comment by KirkBushman** [comment]
Ok, this is merged and working, can you please make a new release, so I can try it?
