### ISSUE TITLE
Scaling by double-clicking on the display

### ISSUE THREAD

**Issue by Alexander178** [Piasy/BigImageViewer#99]
Hello, how do I set the amount of zoom to double-click on the display?
Something like:
~BigImgView.setDoubleTapZoomScale ( 2.5f );

**Comment by Piasy** [comment]
I think that depends on your image size and device screen size.

**Comment by Alexander178** [comment]
You did not understand a bit, I want to programmatically set the zoom value for double-clicking on the display, so that the image magnification was not maximum, but for example 1/2 of the maximum ... How can this be done?

**Comment by Piasy** [comment]
Ok, I think SSIV should have such API, please check its docs, https://github.com/davemorrissey/subsampling-scale-image-view

**Comment by Alexander178** [comment]
I did not find a method to limit the amount of scaling when double-clicking on the display. Maybe you will add this feature in the future ... I understand, you have the maximum zoom in the image to double-click on the display, and it does not change by the user ...

**Comment by Alexander178** [comment]
Hello, tell me please how to catch an event, that the image is already downloaded? I have a black screen for a few seconds when I load a large image from a file, I want to do this while the screen is black, my Progress Bar.

**Comment by Piasy** [comment]
Any update on this issue?

**Comment by Piasy** [comment]
Closing it now, feel free to reopen it.
